import { describe, expect, it } from 'vitest';
import { decodeClawBackendEvent } from '../backend-protocol/events';

const occurredAt = '2026-09-04T12:00:00.000Z';
const usage = {
  totalTokens: 10,
  inputTokens: 4,
  cachedInputTokens: 1,
  outputTokens: 5,
  reasoningOutputTokens: 2,
  lastTotalTokens: 9,
  modelContextWindow: 1000,
  usedPercent: 1,
};
const message = {
  id: 'message-1',
  agentId: 'agent-1',
  role: 'assistant' as const,
  status: 'complete' as const,
  parts: [{ type: 'text' as const, text: 'Done' }],
  createdAt: occurredAt,
};
const toolPart = {
  type: 'tool' as const,
  id: 'tool-1',
  kind: 'command',
  title: 'Run tests',
  status: 'completed' as const,
};
const gitStatus = {
  folder: '/repo',
  ahead: 0,
  behind: 0,
  changedFiles: 0,
  addedLines: 0,
  removedLines: 0,
  hasUntracked: false,
  state: 'clean' as const,
  updatedAt: occurredAt,
};
const approval = {
  id: 'approval-1',
  kind: 'command' as const,
  conversationId: 'thread-1',
  itemId: 'item-1',
  title: 'Run command',
};
const confirmTool = {
  id: 'request-1',
  kind: 'confirm_tool' as const,
  payload: {
    confirmation: {
      argumentsPreview: 'npm test',
      integrationId: 'shell',
      integrationName: 'Shell',
      summary: 'Run tests',
      toolName: 'exec',
    },
  },
};
const askUser = {
  id: 'request-2',
  kind: 'ask_user' as const,
  payload: {
    request: {
      itemId: 'item-2',
      questions: [
        {
          id: 'question-1',
          header: 'Choice',
          question: 'Continue?',
          isOther: false,
          isSecret: false,
          options: [{ label: 'Yes', description: 'Continue' }],
        },
      ],
    },
  },
};

describe('Claw backend event decoder variants', () => {
  it('accepts fully populated and provider-specific payload alternatives', () => {
    const base = { seq: 2, occurredAt };
    const agent = { ...base, agentId: 'agent-1' };
    const codexThread = { ...agent, backend: 'codex', threadId: 'thread-1' };
    const turn = { ...codexThread, turnId: 'turn-1' };
    const richEvents: unknown[] = [
      {
        ...base,
        type: 'backend.statusChanged',
        backend: 'codex',
        payload: {
          backend: 'claude',
          status: 'error',
          detail: { key: 'backend.error', params: { attempts: 2 } },
          capabilities: {
            attachments: true,
            models: true,
            skills: true,
            reasoningEffort: true,
            serviceTier: true,
            thinkingBudget: true,
            planMode: 'native',
            goals: true,
            steerPrompt: true,
            interrupt: true,
            history: true,
            conversationFork: true,
            deleteTurn: true,
            editTurn: true,
            retryTurn: true,
            approvals: true,
            approvalPresets: ['ask-for-approval'],
            permissionModes: [
              {
                id: 'full',
                label: 'Full',
                description: 'Everything',
                dangerous: true,
              },
            ],
          },
        },
      },
      {
        ...base,
        type: 'client.connectionChanged',
        payload: { status: 'error', detail: { key: 'offline' } },
      },
      {
        ...base,
        type: 'account.rateLimitsUpdated',
        backend: 'codex',
        payload: {
          rateLimits: {
            limitId: 'limit',
            limitName: 'Limit',
            primary: { usedPercent: 10, windowDurationMins: 60, resetsAt: 1 },
            secondary: {
              usedPercent: 20,
              windowDurationMins: null,
              resetsAt: null,
            },
            credits: {},
            individualLimit: [],
            planType: 'pro',
            rateLimitReachedType: 'primary',
          },
        },
      },
      {
        ...base,
        type: 'devicePairing.statusChanged',
        payload: {
          status: 'errored',
          serverName: 'server',
          installationId: 'installation',
          environmentId: null,
          allowRemoteControl: false,
          detail: 'offline',
        },
      },
      {
        ...base,
        type: 'models.changed',
        backend: 'codex',
        payload: {
          models: [
            {
              id: 'gpt',
              model: 'gpt',
              displayName: 'GPT',
              description: 'Model',
              hidden: false,
              supportedReasoningEfforts: [
                { reasoningEffort: 'high', description: 'High' },
              ],
              defaultReasoningEffort: null,
              serviceTiers: [
                { id: 'priority', name: 'Priority', description: 'Fast' },
              ],
              defaultServiceTier: null,
              isDefault: true,
              capabilities: { planMode: 'prompted' },
              providerMetadata: {},
            },
          ],
        },
      },
      {
        ...base,
        type: 'skills.changed',
        backend: 'claude',
        payload: {
          cwd: '/repo',
          status: 'loaded',
          skills: [
            {
              id: 'skill',
              name: 'Skill',
              description: 'Description',
              shortDescription: 'Short',
              displayName: 'Display',
              iconSmall: 'small',
              iconLarge: 'large',
              brandColor: '#fff',
              defaultPrompt: 'Prompt',
              path: '/skill',
              scope: 'repo',
              enabled: false,
              providerMetadata: {},
            },
          ],
        },
      },
      {
        ...agent,
        type: 'sidePanel.markdownRequested',
        payload: {
          kind: 'markdown',
          purpose: 'plan',
          title: { key: 'plan.title' },
          path: '/plan.md',
          content: 'Plan',
        },
      },
      {
        ...agent,
        type: 'sidePanel.gitDiffRequested',
        payload: {
          kind: 'gitDiff',
          scope: 'turn',
          title: 'Diff',
          subtitle: null,
          diff: '+line',
          sections: [{ scope: 'staged', diff: '+line' }],
          state: 'error',
          error: null,
        },
      },
      {
        ...agent,
        type: 'agentCreation.progress',
        payload: {
          id: 'creation',
          state: 'success',
          backend: 'claude',
          repositoryName: 'repo',
          createWorktree: false,
          branchName: 'feature',
          hasPrompt: false,
          phase: 'startingPrompt',
          initializationDetail: 'ready',
          agentId: 'agent-2',
          agentName: 'Worker',
          error: 'none',
        },
      },
      {
        ...base,
        type: 'browser.annotationCreated',
        payload: {
          id: 'annotation',
          agentId: 'agent-1',
          browserId: 'primary',
          url: 'https://example.com',
          kind: 'element',
          selector: '#app',
          label: 'App',
          comment: 'Review',
          rect: { x: 0, y: 0, width: 10, height: 10 },
        },
      },
      {
        ...base,
        type: 'workBacklog.assignmentUpdated',
        payload: {
          provider: 'github',
          itemId: '7',
          agentId: 'agent-1',
          assignedAt: occurredAt,
          policy: 'review',
          status: 'readyForReview',
          completedAt: occurredAt,
          note: 'Done',
          updatedAt: occurredAt,
          automationId: 'automation',
          automationExecutionId: 'execution',
        },
      },
      {
        ...agent,
        type: 'agent.updated',
        payload: {
          id: 'agent-1',
          teamId: 'team-1',
          delegatedByAgentId: 'agent-0',
          name: null,
          conversationTitle: 'Title',
          avatar: 'avatar',
          folder: null,
          statusText: null,
          sessionKind: 'quickChat',
          backend: 'codex',
          workspace: {
            kind: 'git',
            folder: '/repo',
            repositoryName: 'repo',
            repositoryRoot: '/repo',
            branch: null,
            isLinkedWorktree: false,
            primaryWorktreeRoot: '/repo',
            originUrl: 'git@example.com',
            updatedAt: occurredAt,
          },
          backendSession: {
            kind: 'claude',
            sessionId: 'session',
            transport: 'websocket',
            transcriptSessionId: 'transcript',
            serverUrl: 'ws://server',
            model: 'opus',
            reasoningEffort: 'high',
          },
          backendDefaults: {
            kind: 'claude',
            model: 'opus',
            reasoningEffort: 'high',
            permissionMode: 'default',
            thinking: { type: 'enabled', budgetTokens: 100 },
          },
          openInApplication: 'vscode',
          contextUsage: usage,
          plan: {
            threadId: 'thread-1',
            turnId: 'turn-1',
            kind: 'execution',
            status: 'inProgress',
            explanation: 'Plan',
            steps: [{ step: 'Test', status: 'completed' }],
            markdown: 'Plan',
            updatedAt: occurredAt,
          },
          goal: {
            threadId: 'thread-1',
            objective: 'Ship',
            status: 'blocked',
            tokenBudget: 100,
            tokensUsed: 10,
            timeUsedSeconds: 2,
            createdAt: 1,
            updatedAt: 2,
          },
          pullRequest: {
            provider: 'github',
            repository: 'owner/repo',
            branch: 'feature',
            createdAt: occurredAt,
            updatedAt: occurredAt,
            number: 7,
            title: 'PR',
            url: 'https://example.com/pr',
            draft: false,
            headSha: 'abc',
            state: 'merged',
            mergedAt: occurredAt,
          },
          isRegistered: true,
          mcpSessionId: 'mcp',
          status: { type: 'working', detail: { key: 'working' } },
          createdAt: occurredAt,
          updatedAt: occurredAt,
        },
      },
      {
        ...agent,
        type: 'agent.statusChanged',
        payload: { type: 'error', message: { key: 'failed' } },
      },
      {
        ...agent,
        backend: 'claude',
        backendSessionId: 'session',
        type: 'thread.started',
        payload: {
          sessionId: 'session',
          transport: 'stdio',
          model: 'opus',
          reasoningEffort: 'high',
        },
      },
      {
        ...codexThread,
        type: 'thread.settingsUpdated',
        payload: {
          threadSettings: {
            cwd: '/repo',
            model: 'gpt',
            reasoningEffort: 'high',
            serviceTier: null,
            approvalPolicy: 'on-request',
            approvalsReviewer: 'user',
            sandboxPolicy: { type: 'workspace-write' },
            activePermissionProfile: { id: 'default' },
          },
        },
      },
      {
        ...agent,
        backend: 'claude',
        turnId: 'turn-1',
        type: 'thread.modeUpdated',
        payload: {
          mode: 'default',
          provider: 'claude',
          permissionMode: 'acceptEdits',
        },
      },
      {
        ...agent,
        threadId: 'thread-1',
        type: 'thread.goalUpdated',
        payload: {
          goal: {
            threadId: 'thread-1',
            objective: 'Ship',
            status: 'complete',
            tokenBudget: null,
            tokensUsed: 20,
            timeUsedSeconds: 3,
            createdAt: 1,
            updatedAt: 2,
          },
        },
      },
      {
        ...codexThread,
        type: 'thread.tokenUsageUpdated',
        payload: { contextUsage: usage },
      },
      {
        ...agent,
        type: 'thread.historyLoaded',
        payload: {
          messages: [message],
          replace: true,
          preserveKnownTurns: true,
          preserveKnownMessages: false,
          hasOlderMessages: true,
        },
      },
      {
        ...codexThread,
        type: 'subagent.operationChanged',
        payload: {
          rootConversationId: 'thread-1',
          operation: {
            id: 'operation',
            turnId: 'turn-1',
            lifecycle: 'completed',
            kind: 'sendMessage',
            status: 'completed',
            senderConversationId: 'thread-1',
            receiverConversationIds: ['child'],
            prompt: 'Work',
            model: 'gpt',
            reasoningEffort: 'high',
            occurredAt,
          },
          agentStates: { child: { status: 'completed', message: 'Done' } },
        },
      },
      {
        ...codexThread,
        type: 'subagent.activityChanged',
        payload: {
          rootConversationId: 'thread-1',
          parentConversationId: 'thread-1',
          activity: {
            id: 'activity',
            turnId: 'turn-1',
            lifecycle: 'completed',
            kind: 'completed',
            conversationId: 'child',
            agentPath: 'child',
            occurredAt,
          },
        },
      },
      {
        ...codexThread,
        type: 'subagent.identityChanged',
        payload: {
          rootConversationId: 'thread-1',
          conversationId: 'child',
          agentNickname: 'Worker',
          agentRole: 'reviewer',
        },
      },
      {
        ...codexThread,
        type: 'subagent.statusChanged',
        payload: {
          rootConversationId: 'thread-1',
          conversationId: 'child',
          status: 'errored',
          statusMessage: 'Failed',
        },
      },
      {
        ...agent,
        backend: 'claude',
        turnId: 'turn-1',
        type: 'turn.started',
        payload: { turn: { id: 'turn-1', backend: 'claude' } },
      },
      {
        ...turn,
        type: 'turn.completed',
        payload: {
          status: 'failed',
          error: {
            message: 'Failed',
            additionalDetails: null,
            codexErrorInfo: {},
          },
          willRetry: true,
          startedAt: null,
          completedAt: occurredAt,
          durationMs: 12,
        },
      },
      {
        ...agent,
        backend: 'claude',
        turnId: 'turn-1',
        type: 'turn.completed',
        payload: { turn: { id: 'turn-1', status: 'interrupted' } },
      },
      {
        ...turn,
        type: 'context.compactionStarted',
        payload: { itemId: 'compact-1' },
      },
      {
        ...agent,
        type: 'message.steer',
        payload: {
          prompt: 'Continue',
          attachments: [
            {
              type: 'image',
              path: '/image.png',
              detail: 'high',
              name: 'image',
              mimeType: 'image/png',
              previewUrl: 'data:',
            },
            {
              type: 'file',
              path: '/file.txt',
              name: 'file',
              mimeType: 'text/plain',
            },
          ],
        },
      },
      {
        ...agent,
        type: 'agent.promptQueued',
        payload: {
          id: 'prompt',
          text: 'Work',
          submitted: true,
          options: {
            attachments: [{ type: 'file', path: '/file' }],
            model: null,
            planMode: true,
            reasoningEffort: null,
            serviceTier: null,
            skills: [{ name: 'skill', path: '/skill' }],
            inputMethod: 'dictated',
            backendOptions: {
              kind: 'claude',
              thinkingBudgetTokens: null,
              permissionMode: null,
            },
          },
        },
      },
      {
        ...agent,
        type: 'agent.promptRetryScheduled',
        payload: {
          id: 'prompt',
          attempts: 2,
          lastError: 'Failed',
          retryAt: occurredAt,
        },
      },
      {
        ...turn,
        type: 'item.started',
        payload: {
          messageId: 'message',
          toolPart: {
            ...toolPart,
            statusText: 'Done',
            body: 'Output',
            input: {},
            output: [],
            metadata: {},
          },
        },
      },
      {
        ...turn,
        type: 'item.updated',
        payload: {
          itemId: 'tool',
          messageId: 'message',
          title: 'Tool',
          status: 'failed',
          statusText: null,
          body: 'body',
          bodyDelta: 'delta',
          bodyAppend: 'append',
          input: {},
          output: [],
          metadata: {},
          fallbackToolPart: toolPart,
        },
      },
      {
        ...turn,
        type: 'diff.updated',
        payload: { addedLines: 2, removedLines: 1, diff: '+a' },
      },
      {
        ...agent,
        type: 'git.statusUpdated',
        payload: {
          ...gitStatus,
          repository: 'repo',
          githubRepository: 'owner/repo',
          branch: 'main',
          upstream: 'origin/main',
          error: 'none',
        },
      },
      {
        ...codexThread,
        type: 'approval.requested',
        payload: {
          ...confirmTool,
          payload: {
            confirmation: {
              ...confirmTool.payload.confirmation,
              allowConversation: true,
              allowAlways: false,
            },
          },
        },
      },
      {
        ...codexThread,
        type: 'toolInput.requested',
        payload: {
          ...askUser,
          payload: {
            request: {
              itemId: 'item',
              questions: [
                {
                  id: 'q',
                  header: 'H',
                  question: 'Q',
                  isOther: true,
                  isSecret: true,
                  multiSelect: true,
                  options: null,
                },
              ],
            },
          },
        },
      },
      {
        ...codexThread,
        type: 'backendApproval.resolved',
        payload: {
          approval: {
            ...approval,
            turnId: 'turn-1',
            description: 'Description',
            command: 'npm test',
            cwd: '/repo',
            requestedPermissions: [
              { kind: 'filesystem', access: 'write', path: '/repo' },
              {
                kind: 'network',
                enabled: true,
                host: 'example.com',
                protocol: 'https',
              },
            ],
            allowedScopes: ['once', 'session'],
            canDeny: true,
          },
          decision: null,
          scope: null,
          reason: 'surface_disconnected',
        },
      },
      {
        ...agent,
        type: 'error',
        payload: {
          message: 'Failed',
          willRetry: true,
          error: { code: 'unknown' },
        },
      },
    ];

    for (const event of richEvents)
      expect(decodeClawBackendEvent(event)).toBe(event);
  });
});
