import type { AppearanceMode, AppThemeSettings } from '../../shared/contracts';

export type AppThemeDefinition = {
  id: string;
  name: string;
  appearance: Exclude<AppearanceMode, 'system'>;
  colors: Record<string, string>;
};

type ThemeSeed = {
  id: string;
  name: string;
  appearance: AppThemeDefinition['appearance'];
  primary: string;
  secondary: string;
  surface: string;
  surfaceLowest: string;
  surfaceLow: string;
  surfaceBase: string;
  surfaceHigh: string;
  surfaceHighest: string;
  text: string;
  muted: string;
  outline: string;
  outlineVariant: string;
};

const codexClawSystemPair = {
  light: 'codex-claw-light',
  dark: 'codex-claw-dark',
} as const;

const themePairsById: Record<string, { light: string; dark: string }> = {
  'codex-claw-light': codexClawSystemPair,
  'codex-claw-dark': codexClawSystemPair,
  'codex-claw-dark-blue': {
    light: 'codex-claw-light',
    dark: 'codex-claw-dark-blue',
  },
};

const unsortedAppThemes: AppThemeDefinition[] = [
  theme({
    id: 'codex-claw-light',
    name: 'Codex Claw Light',
    appearance: 'light',
    primary: '#1B4FB2',
    secondary: '#0C72EE',
    surface: '#FAFAFA',
    surfaceLowest: '#FFFFFF',
    surfaceLow: '#F4F4F5',
    surfaceBase: '#F0F0F0',
    surfaceHigh: '#E9E9EC',
    surfaceHighest: '#E4E4E7',
    text: '#27272A',
    muted: '#71717A',
    outline: '#A1A1AA',
    outlineVariant: '#D9D9DD',
  }),
  theme({
    id: 'codex-claw-dark',
    name: 'Codex Claw Dark',
    appearance: 'dark',
    primary: 'rgb(11, 132, 255)',
    secondary: 'rgb(65, 156, 255)',
    surface: '#202020',
    surfaceLowest: '#202020',
    surfaceLow: '#303030',
    surfaceBase: '#303030',
    surfaceHigh: '#404040',
    surfaceHighest: '#505050',
    text: 'rgb(255, 255, 255)',
    muted: '#D0D0D0',
    outline: '#787878',
    outlineVariant: '#646464',
  }),
  theme({
    id: 'codex-claw-dark-blue',
    name: 'Codex Claw Dark Blue',
    appearance: 'dark',
    primary: 'rgb(10, 120, 240)',
    secondary: 'rgb(60, 140, 230)',
    surface: 'rgb(0, 31, 55)',
    surfaceLowest: 'rgb(0, 31, 55)',
    surfaceLow: 'rgb(10, 44, 68)',
    surfaceBase: 'rgb(10, 44, 68)',
    surfaceHigh: 'rgb(40, 50, 65)',
    surfaceHighest: 'rgb(50, 60, 75)',
    text: 'rgb(255, 255, 255)',
    muted: 'rgb(190, 210, 230)',
    outline: 'rgb(100, 110, 120)',
    outlineVariant: 'rgb(45, 65, 85)',
  }),
  theme({
    id: 'absolutely-light',
    name: 'Absolutely Light',
    appearance: 'light',
    primary: '#cc7d5e',
    secondary: '#b26344',
    surface: '#f3f3f1',
    surfaceLowest: '#f9f9f7',
    surfaceLow: '#f3f3f1',
    surfaceBase: '#eeeeec',
    surfaceHigh: '#e9e9e7',
    surfaceHighest: '#dfdfdd',
    text: '#2d2d2b',
    muted: '#747472',
    outline: '#dfdfdd',
    outlineVariant: '#e9e9e7',
  }),
  theme({
    id: 'absolutely-dark',
    name: 'Absolutely Dark',
    appearance: 'dark',
    primary: '#cc7d5e',
    secondary: '#e59677',
    surface: '#373735',
    surfaceLowest: '#272725',
    surfaceLow: '#373735',
    surfaceBase: '#3e3e3c',
    surfaceHigh: '#464644',
    surfaceHighest: '#535351',
    text: '#f9f9f7',
    muted: '#b1b1af',
    outline: '#535351',
    outlineVariant: '#464644',
  }),
  theme({
    id: 'ayu-dark',
    name: 'Ayu Dark',
    appearance: 'dark',
    primary: '#e6b450',
    secondary: '#ffcd69',
    surface: '#15181e',
    surfaceLowest: '#05080e',
    surfaceLow: '#15181e',
    surfaceBase: '#1c1f25',
    surfaceHigh: '#24272d',
    surfaceHighest: '#31343a',
    text: '#bfbdb6',
    muted: '#807f7d',
    outline: '#31343a',
    outlineVariant: '#24272d',
  }),
  theme({
    id: 'cappuccin-latte',
    name: 'Cappuccin Latte',
    appearance: 'light',
    primary: '#1e66f5',
    secondary: '#8839ef',
    surface: '#eff1f5',
    surfaceLowest: '#eff1f5',
    surfaceLow: '#e6e9ef',
    surfaceBase: '#dce0e8',
    surfaceHigh: '#ccd0da',
    surfaceHighest: '#acb0be',
    text: '#4c4f69',
    muted: '#6c6f85',
    outline: '#9ca0b0',
    outlineVariant: '#dce0e8',
  }),
  theme({
    id: 'cappuccin-mocha',
    name: 'Cappuccin Mocha',
    appearance: 'dark',
    primary: '#89b4fa',
    secondary: '#cba6f7',
    surface: '#1e1e2e',
    surfaceLowest: '#11111b',
    surfaceLow: '#181825',
    surfaceBase: '#313244',
    surfaceHigh: '#45475a',
    surfaceHighest: '#585b70',
    text: '#cdd6f4',
    muted: '#a6adc8',
    outline: '#7f849c',
    outlineVariant: '#313244',
  }),
  theme({
    id: 'dracula-dark',
    name: 'Dracula Dark',
    appearance: 'dark',
    primary: '#ff79c6',
    secondary: '#ff92df',
    surface: '#323440',
    surfaceLowest: '#222430',
    surfaceLow: '#323440',
    surfaceBase: '#393b47',
    surfaceHigh: '#41434f',
    surfaceHighest: '#4e505c',
    text: '#f8f8f2',
    muted: '#afafb0',
    outline: '#4e505c',
    outlineVariant: '#41434f',
  }),
  theme({
    id: 'everforest-light',
    name: 'Everforest Light',
    appearance: 'light',
    primary: '#3a94c5',
    secondary: '#35a77c',
    surface: '#fdf6e3',
    surfaceLowest: '#fdf6e3',
    surfaceLow: '#f4f0d9',
    surfaceBase: '#efebd4',
    surfaceHigh: '#e6e2cc',
    surfaceHighest: '#d5c9ab',
    text: '#5c6a72',
    muted: '#829181',
    outline: '#a6b0a0',
    outlineVariant: '#e6e2cc',
  }),
  theme({
    id: 'everforest-dark',
    name: 'Everforest Dark',
    appearance: 'dark',
    primary: '#7fbbb3',
    secondary: '#a7c080',
    surface: '#2d353b',
    surfaceLowest: '#1e2326',
    surfaceLow: '#272e33',
    surfaceBase: '#343f44',
    surfaceHigh: '#3d484d',
    surfaceHighest: '#4f5b58',
    text: '#d3c6aa',
    muted: '#9da9a0',
    outline: '#859289',
    outlineVariant: '#475258',
  }),
  theme({
    id: 'github-light',
    name: 'GitHub Light',
    appearance: 'light',
    primary: '#0969da',
    secondary: '#8250df',
    surface: '#f6f8fa',
    surfaceLowest: '#ffffff',
    surfaceLow: '#f6f8fa',
    surfaceBase: '#eaeef2',
    surfaceHigh: '#d8dee4',
    surfaceHighest: '#afb8c1',
    text: '#1f2328',
    muted: '#656d76',
    outline: '#8c959f',
    outlineVariant: '#d0d7de',
  }),
  theme({
    id: 'github-dark',
    name: 'GitHub Dark',
    appearance: 'dark',
    primary: '#2f81f7',
    secondary: '#58a6ff',
    surface: '#0d1117',
    surfaceLowest: '#010409',
    surfaceLow: '#161b22',
    surfaceBase: '#21262d',
    surfaceHigh: '#30363d',
    surfaceHighest: '#484f58',
    text: '#e6edf3',
    muted: '#8b949e',
    outline: '#6e7681',
    outlineVariant: '#30363d',
  }),
  theme({
    id: 'gruvbox-light',
    name: 'Gruvbox Light',
    appearance: 'light',
    primary: '#076678',
    secondary: '#8f3f71',
    surface: '#fbf1c7',
    surfaceLowest: '#fbf1c7',
    surfaceLow: '#f2e5bc',
    surfaceBase: '#ebdbb2',
    surfaceHigh: '#d5c4a1',
    surfaceHighest: '#bdae93',
    text: '#3c3836',
    muted: '#7c6f64',
    outline: '#928374',
    outlineVariant: '#d5c4a1',
  }),
  theme({
    id: 'gruvbox-dark',
    name: 'Gruvbox Dark',
    appearance: 'dark',
    primary: '#83a598',
    secondary: '#d3869b',
    surface: '#282828',
    surfaceLowest: '#1d2021',
    surfaceLow: '#32302f',
    surfaceBase: '#3c3836',
    surfaceHigh: '#504945',
    surfaceHighest: '#665c54',
    text: '#ebdbb2',
    muted: '#bdae93',
    outline: '#928374',
    outlineVariant: '#504945',
  }),
  theme({
    id: 'linear-light',
    name: 'Linear Light',
    appearance: 'light',
    primary: '#5e6ad2',
    secondary: '#4450b8',
    surface: '#f6f6f7',
    surfaceLowest: '#fcfcfd',
    surfaceLow: '#f6f6f7',
    surfaceBase: '#f1f1f2',
    surfaceHigh: '#ececed',
    surfaceHighest: '#e2e2e3',
    text: '#1b1b1b',
    muted: '#69696a',
    outline: '#c9c9cc',
    outlineVariant: '#e2e2e3',
  }),
  theme({
    id: 'linear-dark',
    name: 'Linear Dark',
    appearance: 'dark',
    primary: '#606acc',
    secondary: '#7983e5',
    surface: '#19191b',
    surfaceLowest: '#09090b',
    surfaceLow: '#19191b',
    surfaceBase: '#202022',
    surfaceHigh: '#28282a',
    surfaceHighest: '#353537',
    text: '#e3e4e6',
    muted: '#98999b',
    outline: '#55555a',
    outlineVariant: '#28282a',
  }),
  theme({
    id: 'lobster-dark',
    name: 'Lobster Dark',
    appearance: 'dark',
    primary: '#ff5c5c',
    secondary: '#ff7575',
    surface: '#1b2231',
    surfaceLowest: '#0b1221',
    surfaceLow: '#1b2231',
    surfaceBase: '#222938',
    surfaceHigh: '#2a3140',
    surfaceHighest: '#373e4d',
    text: '#e4e4e7',
    muted: '#9a9ca3',
    outline: '#373e4d',
    outlineVariant: '#2a3140',
  }),
  theme({
    id: 'material-dark',
    name: 'Material Dark',
    appearance: 'dark',
    primary: '#80cbc4',
    secondary: '#99e4dd',
    surface: '#2b2b2b',
    surfaceLowest: '#1b1b1b',
    surfaceLow: '#2b2b2b',
    surfaceBase: '#323232',
    surfaceHigh: '#3a3a3a',
    surfaceHighest: '#474747',
    text: '#eeffff',
    muted: '#a6b1b1',
    outline: '#474747',
    outlineVariant: '#3a3a3a',
  }),
  theme({
    id: 'matrix-dark',
    name: 'Matrix Dark',
    appearance: 'dark',
    primary: '#1eff5a',
    secondary: '#37ff73',
    surface: '#0e120f',
    surfaceLowest: '#000200',
    surfaceLow: '#0e120f',
    surfaceBase: '#151916',
    surfaceHigh: '#1d211e',
    surfaceHighest: '#2a2e2b',
    text: '#b8ffca',
    muted: '#79a885',
    outline: '#2a2e2b',
    outlineVariant: '#1d211e',
  }),
  theme({
    id: 'monokai-dark',
    name: 'Monokai Dark',
    appearance: 'dark',
    primary: '#99947c',
    secondary: '#b2ad95',
    surface: '#31322c',
    surfaceLowest: '#21221c',
    surfaceLow: '#31322c',
    surfaceBase: '#383933',
    surfaceHigh: '#40413b',
    surfaceHighest: '#4d4e48',
    text: '#f8f8f2',
    muted: '#aeafa9',
    outline: '#4d4e48',
    outlineVariant: '#40413b',
  }),
  theme({
    id: 'night-owl-dark',
    name: 'Night Owl',
    appearance: 'dark',
    primary: '#44596b',
    secondary: '#5d7284',
    surface: '#0b2031',
    surfaceLowest: '#001021',
    surfaceLow: '#0b2031',
    surfaceBase: '#122738',
    surfaceHigh: '#1a2f40',
    surfaceHighest: '#273c4d',
    text: '#d6deeb',
    muted: '#8b98a6',
    outline: '#273c4d',
    outlineVariant: '#1a2f40',
  }),
  theme({
    id: 'nord-dark',
    name: 'Nord Dark',
    appearance: 'dark',
    primary: '#88c0d0',
    secondary: '#a1d9e9',
    surface: '#383e4a',
    surfaceLowest: '#282e3a',
    surfaceLow: '#383e4a',
    surfaceBase: '#3f4551',
    surfaceHigh: '#474d59',
    surfaceHighest: '#545a66',
    text: '#d8dee9',
    muted: '#9ca2ad',
    outline: '#545a66',
    outlineVariant: '#474d59',
  }),
  theme({
    id: 'notion-light',
    name: 'Notion Light',
    appearance: 'light',
    primary: '#2383e2',
    secondary: '#a35f2a',
    surface: '#f7f6f3',
    surfaceLowest: '#ffffff',
    surfaceLow: '#f7f6f3',
    surfaceBase: '#efeeea',
    surfaceHigh: '#e7e6e3',
    surfaceHighest: '#d3d1cb',
    text: '#37352f',
    muted: '#787774',
    outline: '#a8a29b',
    outlineVariant: '#ddd9d2',
  }),
  theme({
    id: 'notion-dark',
    name: 'Notion Dark',
    appearance: 'dark',
    primary: '#2383e2',
    secondary: '#d9734e',
    surface: '#191919',
    surfaceLowest: '#121212',
    surfaceLow: '#202020',
    surfaceBase: '#2a2a2a',
    surfaceHigh: '#373737',
    surfaceHighest: '#4a4a4a',
    text: '#ededed',
    muted: '#a3a3a3',
    outline: '#6b6b6b',
    outlineVariant: '#373737',
  }),
  theme({
    id: 'one-light',
    name: 'One Light',
    appearance: 'light',
    primary: '#4078f2',
    secondary: '#0184bc',
    surface: '#fafafa',
    surfaceLowest: '#fafafa',
    surfaceLow: '#f4f4f4',
    surfaceBase: '#eeeeee',
    surfaceHigh: '#dfdfdf',
    surfaceHighest: '#c8c8c8',
    text: '#383a42',
    muted: '#696c77',
    outline: '#a0a1a7',
    outlineVariant: '#dfdfdf',
  }),
  theme({
    id: 'one-dark-pro',
    name: 'One Dark',
    appearance: 'dark',
    primary: '#61afef',
    secondary: '#56b6c2',
    surface: '#282c34',
    surfaceLowest: '#21252b',
    surfaceLow: '#282c34',
    surfaceBase: '#2c313a',
    surfaceHigh: '#3a3f4b',
    surfaceHighest: '#4b5263',
    text: '#abb2bf',
    muted: '#828997',
    outline: '#5c6370',
    outlineVariant: '#3a3f4b',
  }),
  theme({
    id: 'oscurange-dark',
    name: 'Oscurange Dark',
    appearance: 'dark',
    primary: '#f9b98c',
    secondary: '#ffd2a5',
    surface: '#151519',
    surfaceLowest: '#050509',
    surfaceLow: '#151519',
    surfaceBase: '#1c1c20',
    surfaceHigh: '#242428',
    surfaceHighest: '#313135',
    text: '#e6e6e6',
    muted: '#99999a',
    outline: '#313135',
    outlineVariant: '#242428',
  }),
  theme({
    id: 'proof-light',
    name: 'Proof',
    appearance: 'light',
    primary: '#3d755d',
    secondary: '#235b43',
    surface: '#efede7',
    surfaceLowest: '#f5f3ed',
    surfaceLow: '#efede7',
    surfaceBase: '#eae8e2',
    surfaceHigh: '#e5e3dd',
    surfaceHighest: '#dbd9d3',
    text: '#2f312d',
    muted: '#747470',
    outline: '#dbd9d3',
    outlineVariant: '#e5e3dd',
  }),
  theme({
    id: 'raycast-light',
    name: 'Raycast Light',
    appearance: 'light',
    primary: '#ff6363',
    secondary: '#138af2',
    surface: '#fcfcfc',
    surfaceLowest: '#ffffff',
    surfaceLow: '#fcfcfc',
    surfaceBase: '#f9f9f9',
    surfaceHigh: '#fdfdfd',
    surfaceHighest: '#e6e6e6',
    text: '#030303',
    muted: '#03030399',
    outline: '#03030333',
    outlineVariant: '#0303031f',
  }),
  theme({
    id: 'raycast-dark',
    name: 'Raycast Dark',
    appearance: 'dark',
    primary: '#ff6363',
    secondary: '#56c2ff',
    surface: '#101010',
    surfaceLowest: '#0a0a0a',
    surfaceLow: '#101010',
    surfaceBase: '#161616',
    surfaceHigh: '#202020',
    surfaceHighest: '#323232',
    text: '#fefefe',
    muted: '#fefefe99',
    outline: '#fefefe33',
    outlineVariant: '#fefefe1f',
  }),
  theme({
    id: 'rose-pine-dawn',
    name: 'Rose Pine Dawn',
    appearance: 'light',
    primary: '#286983',
    secondary: '#907aa9',
    surface: '#faf4ed',
    surfaceLowest: '#fffaf3',
    surfaceLow: '#faf4ed',
    surfaceBase: '#f2e9e1',
    surfaceHigh: '#dfdad9',
    surfaceHighest: '#cecacd',
    text: '#575279',
    muted: '#797593',
    outline: '#9893a5',
    outlineVariant: '#dfdad9',
  }),
  theme({
    id: 'rose-pine-moon',
    name: 'Rose Pine Moon',
    appearance: 'dark',
    primary: '#9ccfd8',
    secondary: '#c4a7e7',
    surface: '#232136',
    surfaceLowest: '#191724',
    surfaceLow: '#2a273f',
    surfaceBase: '#393552',
    surfaceHigh: '#44415a',
    surfaceHighest: '#56526e',
    text: '#e0def4',
    muted: '#908caa',
    outline: '#6e6a86',
    outlineVariant: '#393552',
  }),
  theme({
    id: 'sentry-dark',
    name: 'Sentry',
    appearance: 'dark',
    primary: '#7055f6',
    secondary: '#896eff',
    surface: '#37333f',
    surfaceLowest: '#27232f',
    surfaceLow: '#37333f',
    surfaceBase: '#3e3a46',
    surfaceHigh: '#46424e',
    surfaceHighest: '#534f5b',
    text: '#e6dff9',
    muted: '#a59fb4',
    outline: '#534f5b',
    outlineVariant: '#46424e',
  }),
  theme({
    id: 'solarized-light',
    name: 'Solarized Light',
    appearance: 'light',
    primary: '#268bd2',
    secondary: '#2aa198',
    surface: '#eee8d5',
    surfaceLowest: '#fdf6e3',
    surfaceLow: '#eee8d5',
    surfaceBase: '#e4ddc8',
    surfaceHigh: '#d8cfb0',
    surfaceHighest: '#c6bfa5',
    text: '#073642',
    muted: '#586e75',
    outline: '#93a1a1',
    outlineVariant: '#d5ccb0',
  }),
  theme({
    id: 'solarized-dark',
    name: 'Solarized Dark',
    appearance: 'dark',
    primary: '#268bd2',
    secondary: '#2aa198',
    surface: '#002b36',
    surfaceLowest: '#002b36',
    surfaceLow: '#073642',
    surfaceBase: '#0b3f4b',
    surfaceHigh: '#164b58',
    surfaceHighest: '#235b66',
    text: '#eee8d5',
    muted: '#93a1a1',
    outline: '#657b83',
    outlineVariant: '#164b58',
  }),
  theme({
    id: 'temple-dark',
    name: 'Temple Dark',
    appearance: 'dark',
    primary: '#e4f222',
    secondary: '#fdff3b',
    surface: '#0c1c16',
    surfaceLowest: '#000c06',
    surfaceLow: '#0c1c16',
    surfaceBase: '#13231d',
    surfaceHigh: '#1b2b25',
    surfaceHighest: '#283832',
    text: '#c7e6da',
    muted: '#829b91',
    outline: '#283832',
    outlineVariant: '#1b2b25',
  }),
  theme({
    id: 'tokyo-night-dark',
    name: 'Tokyo Night',
    appearance: 'dark',
    primary: '#3d59a1',
    secondary: '#5672ba',
    surface: '#242530',
    surfaceLowest: '#141520',
    surfaceLow: '#242530',
    surfaceBase: '#2b2c37',
    surfaceHigh: '#33343f',
    surfaceHighest: '#40414c',
    text: '#a9b1d6',
    muted: '#767c98',
    outline: '#40414c',
    outlineVariant: '#33343f',
  }),
  theme({
    id: 'vercel-light',
    name: 'Vercel Light',
    appearance: 'light',
    primary: '#000000',
    secondary: '#0070f7',
    surface: '#ffffff',
    surfaceLowest: '#ffffff',
    surfaceLow: '#fafafa',
    surfaceBase: '#f2f2f2',
    surfaceHigh: '#ebebeb',
    surfaceHighest: '#e6e6e6',
    text: '#171717',
    muted: '#4d4d4d',
    outline: '#a8a8a8',
    outlineVariant: '#e6e6e6',
  }),
  theme({
    id: 'vercel-dark',
    name: 'Vercel Dark',
    appearance: 'dark',
    primary: '#ededed',
    secondary: '#50a8ff',
    surface: '#000000',
    surfaceLowest: '#000000',
    surfaceLow: '#1a1a1a',
    surfaceBase: '#1f1f1f',
    surfaceHigh: '#292929',
    surfaceHighest: '#2e2e2e',
    text: '#ededed',
    muted: '#a0a0a0',
    outline: '#878787',
    outlineVariant: '#454545',
  }),
  theme({
    id: 'vscode-plus-light',
    name: 'VS Code Plus Light',
    appearance: 'light',
    primary: '#007acc',
    secondary: '#0060b2',
    surface: '#f9f9f9',
    surfaceLowest: '#ffffff',
    surfaceLow: '#f9f9f9',
    surfaceBase: '#f4f4f4',
    surfaceHigh: '#efefef',
    surfaceHighest: '#e5e5e5',
    text: '#000000',
    muted: '#595959',
    outline: '#8e8e8e',
    outlineVariant: '#e5e5e5',
  }),
  theme({
    id: 'vscode-plus-dark',
    name: 'VS Code Plus Dark',
    appearance: 'dark',
    primary: '#007acc',
    secondary: '#1993e5',
    surface: '#282828',
    surfaceLowest: '#181818',
    surfaceLow: '#282828',
    surfaceBase: '#2f2f2f',
    surfaceHigh: '#373737',
    surfaceHighest: '#444444',
    text: '#d4d4d4',
    muted: '#949494',
    outline: '#6c6c6c',
    outlineVariant: '#373737',
  }),
  theme({
    id: 'xcode-light',
    name: 'Xcode Light',
    appearance: 'light',
    primary: '#3c93fd',
    secondary: '#82adf3',
    surface: '#f5f5f5',
    surfaceLowest: '#ffffff',
    surfaceLow: '#f5f5f5',
    surfaceBase: '#ececec',
    surfaceHigh: '#eef5fe',
    surfaceHighest: '#d9d7d5',
    text: '#282828',
    muted: '#565456',
    outline: '#a6a6a6',
    outlineVariant: '#d9d7d5',
  }),
  theme({
    id: 'xcode-dark',
    name: 'Xcode Dark',
    appearance: 'dark',
    primary: '#3c93fd',
    secondary: '#82adf3',
    surface: '#292a30',
    surfaceLowest: '#1c1d20',
    surfaceLow: '#252629',
    surfaceBase: '#292a30',
    surfaceHigh: '#2f3239',
    surfaceHighest: '#3d4752',
    text: '#ffffff',
    muted: '#a6a7a8',
    outline: '#747478',
    outlineVariant: '#3d4752',
  }),
];

export const appThemes: AppThemeDefinition[] = [...unsortedAppThemes].sort((left, right) => left.name.localeCompare(right.name));

export function themeById(themeId: string): AppThemeDefinition {
  return appThemes.find((themeDefinition) => themeDefinition.id === themeId)
    ?? appThemes.find((themeDefinition) => themeDefinition.id === codexClawSystemPair.light)
    ?? appThemes[0];
}

export function themeIdForAppearance(themeId: string, appearance: AppThemeDefinition['appearance']): string {
  const selectedTheme = themeById(themeId);
  if (selectedTheme.appearance === appearance) {
    return selectedTheme.id;
  }

  const pair = themePairsById[selectedTheme.id];
  if (pair) {
    return pair[appearance];
  }

  return appThemes.find((themeDefinition) => themeDefinition.appearance === appearance)?.id ?? codexClawSystemPair.light;
}

export function effectiveTheme(settings: AppThemeSettings, prefersDark: boolean): AppThemeDefinition {
  if (settings.mode === 'system' && settings.id === codexClawSystemPair.light) {
    return themeById(prefersDark ? codexClawSystemPair.dark : codexClawSystemPair.light);
  }

  return themeById(settings.id);
}

function theme(seed: ThemeSeed): AppThemeDefinition {
  return {
    id: seed.id,
    name: seed.name,
    appearance: seed.appearance,
    colors: {
      '--color-primary': seed.primary,
      '--color-secondary': seed.secondary,
      '--color-surface': seed.surface,
      '--color-surface-lowest': seed.surfaceLowest,
      '--color-surface-low': seed.surfaceLow,
      '--color-surface-base': seed.surfaceBase,
      '--color-surface-high': seed.surfaceHigh,
      '--color-surface-highest': seed.surfaceHighest,
      '--color-on-surface': seed.text,
      '--color-on-surface-variant': seed.muted,
      '--color-outline': seed.outline,
      '--color-outline-variant': seed.outlineVariant,
    },
  };
}
