import type { AppCommand, CodexClawApi, MainToRendererEvent } from './contracts';

export const ipcChannels = {
  respondToThreadFlag: 'agent:thread-flag:respond',
  respondToPlanReview: 'agent:plan-review:respond',
  readEngineInstructions: 'settings:instructions:read',
  saveEngineInstructions: 'settings:instructions:save',
  getSnapshot: 'app:get-snapshot',
  getSnapshotState: 'app:get-snapshot-state',
  listSshHosts: 'connections:ssh-hosts:list',
  addSshConnection: 'connections:ssh:add',
  checkRemoteConnection: 'connections:remote:check',
  updateRemoteConnection: 'connections:remote:update',
  removeRemoteConnection: 'connections:remote:remove',
  getRemoteControlStatus: 'connections:device-pairing:status:get',
  enableRemoteControl: 'connections:device-pairing:enable',
  disableRemoteControl: 'connections:device-pairing:disable',
  startDevicePairing: 'connections:device-pairing:start',
  checkDevicePairing: 'connections:device-pairing:check',
  listPairedDevices: 'connections:device-pairing:devices:list',
  revokePairedDevice: 'connections:device-pairing:device:revoke',
  connectWorkProvider: 'work-provider:connect',
  pollWorkProviderAuthorization: 'work-provider:connection-complete',
  disconnectWorkProvider: 'work-provider:disconnect',
  listWorkRepositories: 'work-provider:repositories:list',
  configureWorkBacklog: 'work-provider:backlog:configure',
  listGlobalWorkItems: 'work-provider:global-items:list',
  listAssignedWorkItems: 'work-provider:assigned-items:list',
  listWorkItems: 'work-provider:items:list',
  listBackendModels: 'backend:models:list',
  listBackendPlugins: 'backend:plugins:list',
  listBackendSkills: 'backend:skills:list',
  listAgentFiles: 'agent:files:list',
  previewAgentFile: 'agent:file:preview',
  getAgentGitDiff: 'agent:git-diff:get',
  getAgentGitWorkflow: 'agent:git-workflow:get',
  generateAgentGitMessage: 'agent:git-workflow:message:generate',
  stageAgentGitFiles: 'agent:git-workflow:stage',
  commitAgentGitChanges: 'agent:git-workflow:commit',
  pushAgentGitBranch: 'agent:git-workflow:push',
  createAgentGitBranch: 'agent:git-workflow:branch:create',
  createAgentGitPullRequest: 'agent:git-workflow:pull-request:create',
  mergeAgentGitBranch: 'agent:git-workflow:merge',
  updateAgentGitBranchFromBase: 'agent:git-workflow:update-from-base',
  getOpenInApplications: 'open-in:applications:get',
  openAgentPath: 'agent:path:open-in',
  chooseAgentFolder: 'agent:choose-folder',
  chooseCodexBinary: 'codex:binary:choose',
  chooseSourceFolder: 'source-folder:choose',
  listSourceFolders: 'source-folder:folders:list',
  listSourceRepositories: 'source-folder:repositories:list',
  cloneSourceRepository: 'source-folder:repository:clone',
  createSourceRepository: 'source-folder:repository:create',
  listSourceBranches: 'source-folder:branches:list',
  listSourceWorktrees: 'source-folder:worktrees:list',
  suggestSourceWorktreePath: 'source-folder:worktree-path:suggest',
  chooseSourceWorktreeDestination: 'source-folder:worktree-destination:choose',
  createSourceWorktree: 'source-folder:worktree:create',
  createTeam: 'team:create',
  updateTeam: 'team:update',
  reorderTeams: 'team:reorder',
  closeTeam: 'team:close',
  disconnectTeam: 'team:disconnect',
  selectTeam: 'team:select',
  getAutomationSnapshot: 'automation:snapshot:get',
  createAutomation: 'automation:create',
  updateAutomation: 'automation:update',
  runAutomation: 'automation:run',
  clearAutomationHistory: 'automation:history:clear',
  deleteAutomationExecution: 'automation:execution:delete',
  deleteAutomation: 'automation:delete',
  listAgentConversations: 'conversation:list',
  resumeAgentConversation: 'conversation:resume',
  compressAgentSession: 'conversation:compress',
  readConversationMessages: 'conversation:messages:read',
  createAgent: 'agent:create',
  createQuickChat: 'agent:quick-chat:create',
  updateAgent: 'agent:update',
  assignWorkItemToAgent: 'agent:work-item:assign',
  removeWorkItemAssignment: 'agent:work-item:unassign',
  duplicateAgent: 'agent:duplicate',
  forkAgent: 'agent:fork',
  moveAgentToTeam: 'agent:move-to-team',
  reorderAgents: 'agent:reorder',
  reorderRepositories: 'repository:reorder',
  restartAgent: 'agent:restart',
  loadConversationHistory: 'agent:history:hydrate',
  loadOlderAgentHistory: 'agent:history:load-older',
  closeAgent: 'agent:close',
  selectAgent: 'agent:select',
  updateSettings: 'settings:update',
  previewSpokenAnnouncementVoice: 'settings:spoken-announcement-voice:preview',
  getCodexResourceSharingStatus: 'settings:codex-resource-sharing:get',
  setCodexResourceSharing: 'settings:codex-resource-sharing:set',
  getPluginStatus: 'settings:plugin-status:get',
  getCodexAuthentication: 'codex:authentication:get',
  cancelCodexChatGptLogin: 'codex:authentication:chatgpt:cancel',
  startCodexChatGptLogin: 'codex:authentication:chatgpt:start',
  startCodexChatGptDeviceCodeLogin: 'codex:authentication:deviceCode:start',
  logoutCodex: 'codex:authentication:logout',
  getUpdateStatus: 'app:update-status:get',
  installUpdate: 'app:update:install',
  setDockBadgeCount: 'app:dock-badge:set',
  getDaemonStatus: 'daemon:status:get',
  setDaemonEnabled: 'daemon:enabled:set',
  getSystemPermissions: 'system-permissions:get',
  openAccessibilitySettings: 'system-permissions:accessibility:open',
  openScreenRecordingSettings: 'system-permissions:screen-recording:open',
  launchChatGptApp: 'chatgpt:app:launch',
  quit: 'app:quit',
  restartApp: 'app:restart',
  reloadRenderer: 'app:renderer:reload',
  setAgentGoal: 'agent:goal:set',
  clearAgentGoal: 'agent:goal:clear',
  setAgentApprovalPreset: 'agent:approval-preset:set',
  setAgentPermissionMode: 'agent:permission-mode:set',
  sendPrompt: 'agent:send-prompt',
  steerPrompt: 'agent:steer-prompt',
  deleteQueuedPrompt: 'agent:delete-queued-prompt',
  steerQueuedPrompt: 'agent:steer-queued-prompt',
  updateQueuedPrompt: 'agent:update-queued-prompt',
  interruptAgent: 'agent:interrupt',
  deleteTurn: 'turn:delete',
  editTurn: 'turn:edit',
  retryTurn: 'turn:retry',
  browserOpen: 'browser:open',
  browserOpenVisualization: 'browser:visualization:open',
  browserNavigate: 'browser:navigate',
  browserGoBack: 'browser:go-back',
  browserGoForward: 'browser:go-forward',
  browserReload: 'browser:reload',
  browserSetBounds: 'browser:bounds:set',
  browserSetVisible: 'browser:visible:set',
  browserSetAnnotationMode: 'browser:annotation-mode:set',
  browserResolveAnnotation: 'browser:annotation:resolve',
  browserClearAnnotations: 'browser:annotations:clear',
  browserClose: 'browser:close',
  respondToClientRequest: 'client-request:respond',
  event: 'app:event',
  appCommand: 'app:command',
  updateStatusChanged: 'app:update-status-changed',
} as const;

type CodexClawIpcRequestApi = Omit<CodexClawApi, 'onAppCommand' | 'onEvent' | 'onUpdateStatusChanged'>;

type IpcRequestFor<Method> = Method extends (...args: infer Arguments) => infer Result
  ? { args: Arguments; result: Awaited<Result> }
  : never;

export type CodexClawIpcRequests = {
  [Name in keyof CodexClawIpcRequestApi as Name extends keyof typeof ipcChannels
    ? (typeof ipcChannels)[Name]
    : never]: IpcRequestFor<CodexClawIpcRequestApi[Name]>;
};

export type CodexClawIpcEvents = {
  [ipcChannels.event]: MainToRendererEvent;
  [ipcChannels.appCommand]: AppCommand;
  [ipcChannels.updateStatusChanged]: import('./contracts').DesktopUpdateStatus;
};
