import { contextBridge, ipcRenderer } from 'electron';
import type { AddSshConnectionInput, AgentGitCommitInput, AgentGitMergeInput, AgentGitPullRequestInput, AgentGitPushInput, AgentGitStageInput, AppCommand, AppPluginStatus, ApprovalPreset, BackendConversationRef, BenchLocation, BrowserBounds, ClientRequestResponse, CodexClawApi, CreateAgentInput, CreateLoopInput, CreateSourceWorktreeInput, CreateTeamInput, DevicePairingSession, DesktopUpdateStatus, LoopLocation, MainToRendererEvent, MoveAgentToTeamInput, OpenInApplication, RendererSendPromptOptions, ReorderAgentsInput, ReorderTeamsInput, SetCodexResourceSharingInput, SourceFolderListInput, UpdateAgentInput, UpdateLoopInput, UpdateRemoteConnectionInput, UpdateSettingsInput, UpdateTeamInput, WorkBacklogConfigurationInput, WorkItem, WorkProviderKind } from '@codex-claw/core/contracts';
import { ipcChannels, type CodexClawIpcEvents, type CodexClawIpcRequests } from '@codex-claw/core/ipc';
import { exposeCodexNativeRendererApi, TypedIpcRenderer } from '@codex-app-sdk/electron/preload';

const ipc = new TypedIpcRenderer<CodexClawIpcRequests, CodexClawIpcEvents>(ipcRenderer);

const api: CodexClawApi = {
  getSnapshot: () => ipc.invoke(ipcChannels.getSnapshot),
  getSnapshotState: () => ipc.invoke(ipcChannels.getSnapshotState),
  listSshHosts: () => ipc.invoke(ipcChannels.listSshHosts),
  addSshConnection: (input: AddSshConnectionInput) => ipc.invoke(ipcChannels.addSshConnection, input),
  checkRemoteConnection: (connectionId: string) => ipc.invoke(ipcChannels.checkRemoteConnection, connectionId),
  updateRemoteConnection: (connectionId: string, input: UpdateRemoteConnectionInput) => ipc.invoke(ipcChannels.updateRemoteConnection, connectionId, input),
  removeRemoteConnection: (connectionId: string) => ipc.invoke(ipcChannels.removeRemoteConnection, connectionId),
  getDevicePairingStatus: () => ipc.invoke(ipcChannels.getDevicePairingStatus),
  enableDevicePairing: () => ipc.invoke(ipcChannels.enableDevicePairing),
  disableDevicePairing: () => ipc.invoke(ipcChannels.disableDevicePairing),
  startDevicePairing: () => ipc.invoke(ipcChannels.startDevicePairing),
  checkDevicePairing: (session: DevicePairingSession) => ipc.invoke(ipcChannels.checkDevicePairing, session),
  listPairedDevices: (environmentId: string) => ipc.invoke(ipcChannels.listPairedDevices, environmentId),
  revokePairedDevice: (environmentId: string, clientId: string) => ipc.invoke(ipcChannels.revokePairedDevice, environmentId, clientId),
  connectWorkProvider: (provider: WorkProviderKind) => ipc.invoke(ipcChannels.connectWorkProvider, provider),
  openWorkProviderAuthorization: (provider: WorkProviderKind) => ipc.invoke(ipcChannels.openWorkProviderAuthorization, provider),
  completeWorkProviderConnection: (provider: WorkProviderKind) => ipc.invoke(ipcChannels.completeWorkProviderConnection, provider),
  disconnectWorkProvider: (provider: WorkProviderKind) => ipc.invoke(ipcChannels.disconnectWorkProvider, provider),
  listWorkRepositories: (provider: WorkProviderKind, location?: LoopLocation) => ipc.invoke(ipcChannels.listWorkRepositories, provider, location),
  configureWorkBacklog: (input: WorkBacklogConfigurationInput, location?: LoopLocation) => ipc.invoke(ipcChannels.configureWorkBacklog, input, location),
  listWorkItems: (provider: WorkProviderKind, repositoryId: string, location?: LoopLocation) => ipc.invoke(ipcChannels.listWorkItems, provider, repositoryId, location),
  listBackendModels: (agentId: string) => ipc.invoke(ipcChannels.listBackendModels, agentId),
  listBackendPlugins: (agentId: string) => ipc.invoke(ipcChannels.listBackendPlugins, agentId),
  listBackendSkills: (agentId: string) => ipc.invoke(ipcChannels.listBackendSkills, agentId),
  listAgentFiles: (agentId: string) => ipc.invoke(ipcChannels.listAgentFiles, agentId),
  previewAgentFile: (agentId: string, filePath: string) => ipc.invoke(ipcChannels.previewAgentFile, agentId, filePath),
  openAgentGitDiff: (agentId: string) => ipc.invoke(ipcChannels.openAgentGitDiff, agentId),
  getAgentGitWorkflow: (agentId: string) => ipc.invoke(ipcChannels.getAgentGitWorkflow, agentId),
  stageAgentGitFiles: (agentId: string, input: AgentGitStageInput) => ipc.invoke(ipcChannels.stageAgentGitFiles, agentId, input),
  commitAgentGitChanges: (agentId: string, input: AgentGitCommitInput) => ipc.invoke(ipcChannels.commitAgentGitChanges, agentId, input),
  pushAgentGitBranch: (agentId: string, input: AgentGitPushInput) => ipc.invoke(ipcChannels.pushAgentGitBranch, agentId, input),
  createAgentGitPullRequest: (agentId: string, input: AgentGitPullRequestInput) => ipc.invoke(ipcChannels.createAgentGitPullRequest, agentId, input),
  mergeAgentGitBranch: (agentId: string, input: AgentGitMergeInput) => ipc.invoke(ipcChannels.mergeAgentGitBranch, agentId, input),
  getOpenInApplications: () => ipc.invoke(ipcChannels.getOpenInApplications),
  openAgentPath: (agentId: string, application: OpenInApplication, filePath?: string) => ipc.invoke(ipcChannels.openAgentPath, agentId, application, filePath),
  chooseAgentFolder: () => ipc.invoke(ipcChannels.chooseAgentFolder),
  chooseCodexBinary: () => ipc.invoke(ipcChannels.chooseCodexBinary),
  chooseSourceFolder: () => ipc.invoke(ipcChannels.chooseSourceFolder),
  listSourceFolders: (input?: SourceFolderListInput) => ipc.invoke(ipcChannels.listSourceFolders, input),
  listSourceRepositories: (remoteConnectionId?: string) => ipc.invoke(ipcChannels.listSourceRepositories, remoteConnectionId),
  listSourceWorktrees: (repoPath: string, remoteConnectionId?: string) => ipc.invoke(ipcChannels.listSourceWorktrees, repoPath, remoteConnectionId),
  suggestSourceWorktreePath: (input: Pick<CreateSourceWorktreeInput, 'branchName' | 'repoPath' | 'remoteConnectionId'>) => ipc.invoke(ipcChannels.suggestSourceWorktreePath, input),
  chooseSourceWorktreeDestination: (defaultPath: string) => ipc.invoke(ipcChannels.chooseSourceWorktreeDestination, defaultPath),
  createSourceWorktree: (input: CreateSourceWorktreeInput) => ipc.invoke(ipcChannels.createSourceWorktree, input),
  createTeam: (input: CreateTeamInput) => ipc.invoke(ipcChannels.createTeam, input),
  updateTeam: (input: UpdateTeamInput) => ipc.invoke(ipcChannels.updateTeam, input),
  reorderTeams: (input: ReorderTeamsInput) => ipc.invoke(ipcChannels.reorderTeams, input),
  closeTeam: (teamId: string) => ipc.invoke(ipcChannels.closeTeam, teamId),
  disconnectTeam: (teamId: string) => ipc.invoke(ipcChannels.disconnectTeam, teamId),
  selectTeam: (teamId: string) => ipc.invoke(ipcChannels.selectTeam, teamId),
  getBenchSnapshot: (location?: BenchLocation) => ipc.invoke(ipcChannels.getBenchSnapshot, location),
  getLoopSnapshot: (location?: LoopLocation) => ipc.invoke(ipcChannels.getLoopSnapshot, location),
  createLoop: (input: CreateLoopInput, location?: LoopLocation) => ipc.invoke(ipcChannels.createLoop, input, location),
  updateLoop: (input: UpdateLoopInput, location?: LoopLocation) => ipc.invoke(ipcChannels.updateLoop, input, location),
  runLoop: (loopId: string, location?: LoopLocation) => ipc.invoke(ipcChannels.runLoop, loopId, location),
  clearLoopHistory: (loopId: string, location?: LoopLocation) => ipc.invoke(ipcChannels.clearLoopHistory, loopId, location),
  deleteLoopExecution: (loopId: string, executionId: string, location?: LoopLocation) => ipc.invoke(ipcChannels.deleteLoopExecution, loopId, executionId, location),
  deleteLoop: (loopId: string, location?: LoopLocation) => ipc.invoke(ipcChannels.deleteLoop, loopId, location),
  listAgentConversations: (agentId: string) => ipc.invoke(ipcChannels.listAgentConversations, agentId),
  resumeAgentConversation: (agentId: string, ref: BackendConversationRef) => ipc.invoke(ipcChannels.resumeAgentConversation, agentId, ref),
  readConversationMessages: (ref: BackendConversationRef, agentId: string, location?: LoopLocation) => ipc.invoke(ipcChannels.readConversationMessages, ref, agentId, location),
  createAgent: (input: CreateAgentInput) => ipc.invoke(ipcChannels.createAgent, input),
  updateAgent: (input: UpdateAgentInput) => ipc.invoke(ipcChannels.updateAgent, input),
  assignWorkItemToAgent: (agentId: string, item: WorkItem) => ipc.invoke(ipcChannels.assignWorkItemToAgent, agentId, item),
  removeWorkItemAssignment: (item: WorkItem) => ipc.invoke(ipcChannels.removeWorkItemAssignment, item),
  duplicateAgent: (agentId: string) => ipc.invoke(ipcChannels.duplicateAgent, agentId),
  forkAgent: (agentId: string, messageIndex?: number) => ipc.invoke(ipcChannels.forkAgent, agentId, messageIndex),
  moveAgentToTeam: (input: MoveAgentToTeamInput) => ipc.invoke(ipcChannels.moveAgentToTeam, input),
  reorderAgents: (input: ReorderAgentsInput) => ipc.invoke(ipcChannels.reorderAgents, input),
  saveAgentToBench: (agentId: string) => ipc.invoke(ipcChannels.saveAgentToBench, agentId),
  deployBenchTemplate: (templateId: string, teamId?: string, location?: BenchLocation) => ipc.invoke(ipcChannels.deployBenchTemplate, templateId, teamId, location),
  removeBenchTemplate: (templateId: string, location?: BenchLocation) => ipc.invoke(ipcChannels.removeBenchTemplate, templateId, location),
  restartAgent: (agentId: string) => ipc.invoke(ipcChannels.restartAgent, agentId),
  hydrateAgentHistory: (agentId: string) => ipc.invoke(ipcChannels.hydrateAgentHistory, agentId),
  loadOlderAgentHistory: (agentId: string) => ipc.invoke(ipcChannels.loadOlderAgentHistory, agentId),
  closeAgent: (agentId: string) => ipc.invoke(ipcChannels.closeAgent, agentId),
  selectAgent: (agentId: string) => ipc.invoke(ipcChannels.selectAgent, agentId),
  updateSettings: (input: UpdateSettingsInput) => ipc.invoke(ipcChannels.updateSettings, input),
  getCodexResourceSharingStatus: () => ipc.invoke(ipcChannels.getCodexResourceSharingStatus),
  setCodexResourceSharing: (input: SetCodexResourceSharingInput) => ipc.invoke(ipcChannels.setCodexResourceSharing, input),
  getPluginStatus: () => ipc.invoke(ipcChannels.getPluginStatus),
  getCodexAuthentication: () => ipc.invoke(ipcChannels.getCodexAuthentication),
  cancelCodexChatGptLogin: () => ipc.invoke(ipcChannels.cancelCodexChatGptLogin),
  startCodexChatGptLogin: () => ipc.invoke(ipcChannels.startCodexChatGptLogin),
  logoutCodex: () => ipc.invoke(ipcChannels.logoutCodex),
  getUpdateStatus: () => ipc.invoke(ipcChannels.getUpdateStatus),
  installUpdate: () => ipc.invoke(ipcChannels.installUpdate),
  setDockBadgeCount: (count: number) => ipc.invoke(ipcChannels.setDockBadgeCount, count),
  getDaemonStatus: () => ipc.invoke(ipcChannels.getDaemonStatus),
  setDaemonEnabled: (enabled: boolean) => ipc.invoke(ipcChannels.setDaemonEnabled, enabled),
  getSystemPermissions: () => ipc.invoke(ipcChannels.getSystemPermissions),
  openAccessibilitySettings: () => ipc.invoke(ipcChannels.openAccessibilitySettings),
  openScreenRecordingSettings: () => ipc.invoke(ipcChannels.openScreenRecordingSettings),
  launchChatGptApp: () => ipc.invoke(ipcChannels.launchChatGptApp),
  quit: () => ipc.invoke(ipcChannels.quit),
  restartApp: () => ipc.invoke(ipcChannels.restartApp),
  reloadRenderer: () => ipc.invoke(ipcChannels.reloadRenderer),
  setAgentGoal: (agentId: string, objective: string) => ipc.invoke(ipcChannels.setAgentGoal, agentId, objective),
  clearAgentGoal: (agentId: string) => ipc.invoke(ipcChannels.clearAgentGoal, agentId),
  setAgentApprovalPreset: (agentId: string, preset: ApprovalPreset) => ipc.invoke(ipcChannels.setAgentApprovalPreset, agentId, preset),
  setAgentPermissionMode: (agentId: string, mode: string) => ipc.invoke(ipcChannels.setAgentPermissionMode, agentId, mode),
  sendPrompt: (agentId: string, prompt: string, options?: RendererSendPromptOptions) => ipc.invoke(ipcChannels.sendPrompt, agentId, prompt, options),
  steerPrompt: (agentId: string, prompt: string, options?: RendererSendPromptOptions) => ipc.invoke(ipcChannels.steerPrompt, agentId, prompt, options),
  deleteQueuedPrompt: (agentId: string, promptId: string) => ipc.invoke(ipcChannels.deleteQueuedPrompt, agentId, promptId),
  steerQueuedPrompt: (agentId: string, promptId: string) => ipc.invoke(ipcChannels.steerQueuedPrompt, agentId, promptId),
  interruptAgent: (agentId: string) => ipc.invoke(ipcChannels.interruptAgent, agentId),
  deleteMessage: (agentId: string, messageId: string) => ipc.invoke(ipcChannels.deleteMessage, agentId, messageId),
  editMessage: (agentId: string, messageId: string, prompt: string) => ipc.invoke(ipcChannels.editMessage, agentId, messageId, prompt),
  retryMessage: (agentId: string, messageId: string) => ipc.invoke(ipcChannels.retryMessage, agentId, messageId),
  browserOpen: (agentId: string, browserId: string, url: string) => ipc.invoke(ipcChannels.browserOpen, agentId, browserId, url),
  browserNavigate: (agentId: string, browserId: string, url: string) => ipc.invoke(ipcChannels.browserNavigate, agentId, browserId, url),
  browserGoBack: (agentId: string, browserId: string) => ipc.invoke(ipcChannels.browserGoBack, agentId, browserId),
  browserGoForward: (agentId: string, browserId: string) => ipc.invoke(ipcChannels.browserGoForward, agentId, browserId),
  browserReload: (agentId: string, browserId: string) => ipc.invoke(ipcChannels.browserReload, agentId, browserId),
  browserSetBounds: (agentId: string, browserId: string, bounds: BrowserBounds) => ipc.invoke(ipcChannels.browserSetBounds, agentId, browserId, bounds),
  browserSetVisible: (agentId: string, browserId: string, visible: boolean) => ipc.invoke(ipcChannels.browserSetVisible, agentId, browserId, visible),
  browserSetAnnotationMode: (agentId: string, browserId: string, enabled: boolean) => ipc.invoke(ipcChannels.browserSetAnnotationMode, agentId, browserId, enabled),
  browserResolveAnnotation: (token: string, comment: string | null) => ipc.invoke(ipcChannels.browserResolveAnnotation, token, comment),
  browserClearAnnotations: (agentId: string, browserId: string) => ipc.invoke(ipcChannels.browserClearAnnotations, agentId, browserId),
  browserClose: (agentId: string, browserId: string) => ipc.invoke(ipcChannels.browserClose, agentId, browserId),
  respondToClientRequest: (response: ClientRequestResponse) => ipc.invoke(ipcChannels.respondToClientRequest, response),
  onEvent: (listener: (event: MainToRendererEvent) => void) => {
    return ipc.on(ipcChannels.event, listener);
  },
  onAppCommand: (listener: (command: AppCommand) => void) => {
    return ipc.on(ipcChannels.appCommand, listener);
  },
  onUpdateStatusChanged: (listener: (status: DesktopUpdateStatus) => void) => {
    return ipc.on(ipcChannels.updateStatusChanged, listener);
  },
};

contextBridge.exposeInMainWorld('codexClaw', api);
exposeCodexNativeRendererApi(contextBridge, ipcRenderer);
