import { contextBridge, ipcRenderer } from 'electron';
import type { AddSshConnectionInput, AppleSpeechTranscriptionOptions, AppCommand, ApprovalPreset, BackendConversationRef, BenchLocation, ClientRequestResponse, CodexClawApi, CreateAgentInput, CreateLoopInput, CreateSourceWorktreeInput, CreateTeamInput, LoopLocation, MainToRendererEvent, MoveAgentToTeamInput, ReorderAgentsInput, ReorderTeamsInput, SendPromptOptions, SourceFolderListInput, UpdateAgentInput, UpdateLoopInput, UpdateRemoteConnectionInput, UpdateSettingsInput, UpdateTeamInput, WorkBacklogConfigurationInput, WorkItem, WorkProviderKind } from '@codex-claw/shared/contracts';
import { ipcChannels, type CodexClawIpcEvents, type CodexClawIpcRequests } from '@codex-claw/shared/ipc';
import { TypedIpcRenderer } from 'codex-app-sdk/electron';

const ipc = new TypedIpcRenderer<CodexClawIpcRequests, CodexClawIpcEvents>(ipcRenderer);

const api: CodexClawApi = {
  getSnapshot: () => ipc.invoke(ipcChannels.getSnapshot),
  listSshHosts: () => ipc.invoke(ipcChannels.listSshHosts),
  addSshConnection: (input: AddSshConnectionInput) => ipc.invoke(ipcChannels.addSshConnection, input),
  checkRemoteConnection: (connectionId: string) => ipc.invoke(ipcChannels.checkRemoteConnection, connectionId),
  updateRemoteConnection: (connectionId: string, input: UpdateRemoteConnectionInput) => ipc.invoke(ipcChannels.updateRemoteConnection, connectionId, input),
  removeRemoteConnection: (connectionId: string) => ipc.invoke(ipcChannels.removeRemoteConnection, connectionId),
  connectWorkProvider: (provider: WorkProviderKind) => ipc.invoke(ipcChannels.connectWorkProvider, provider),
  openWorkProviderAuthorization: (provider: WorkProviderKind) => ipc.invoke(ipcChannels.openWorkProviderAuthorization, provider),
  completeWorkProviderConnection: (provider: WorkProviderKind) => ipc.invoke(ipcChannels.completeWorkProviderConnection, provider),
  disconnectWorkProvider: (provider: WorkProviderKind) => ipc.invoke(ipcChannels.disconnectWorkProvider, provider),
  listWorkRepositories: (provider: WorkProviderKind, location?: LoopLocation) => ipc.invoke(ipcChannels.listWorkRepositories, provider, location),
  configureWorkBacklog: (input: WorkBacklogConfigurationInput, location?: LoopLocation) => ipc.invoke(ipcChannels.configureWorkBacklog, input, location),
  listWorkItems: (provider: WorkProviderKind, repositoryId: string, location?: LoopLocation) => ipc.invoke(ipcChannels.listWorkItems, provider, repositoryId, location),
  listBackendModels: (agentId: string) => ipc.invoke(ipcChannels.listBackendModels, agentId),
  listBackendSkills: (agentId: string) => ipc.invoke(ipcChannels.listBackendSkills, agentId),
  listAgentFiles: (agentId: string) => ipc.invoke(ipcChannels.listAgentFiles, agentId),
  previewAgentFile: (agentId: string, filePath: string) => ipc.invoke(ipcChannels.previewAgentFile, agentId, filePath),
  openAgentGitDiff: (agentId: string) => ipc.invoke(ipcChannels.openAgentGitDiff, agentId),
  chooseAgentFolder: () => ipc.invoke(ipcChannels.chooseAgentFolder),
  chooseCodexBinary: () => ipc.invoke(ipcChannels.chooseCodexBinary),
  chooseSourceFolder: () => ipc.invoke(ipcChannels.chooseSourceFolder),
  listSourceFolders: (input?: SourceFolderListInput) => ipc.invoke(ipcChannels.listSourceFolders, input),
  listSourceRepositories: (remoteConnectionId?: string) => ipc.invoke(ipcChannels.listSourceRepositories, remoteConnectionId),
  listSourceWorktrees: (repoPath: string, remoteConnectionId?: string) => ipc.invoke(ipcChannels.listSourceWorktrees, repoPath, remoteConnectionId),
  suggestSourceWorktreePath: (input: Pick<CreateSourceWorktreeInput, 'branchName' | 'repoPath' | 'remoteConnectionId'>) => ipc.invoke(ipcChannels.suggestSourceWorktreePath, input),
  chooseSourceWorktreeDestination: (defaultPath: string) => ipc.invoke(ipcChannels.chooseSourceWorktreeDestination, defaultPath),
  createSourceWorktree: (input: CreateSourceWorktreeInput) => ipc.invoke(ipcChannels.createSourceWorktree, input),
  createTeam: (input: CreateTeamInput) => ipc.invoke(ipcChannels.createTeam, input),
  updateTeam: (input: UpdateTeamInput) => ipc.invoke(ipcChannels.updateTeam, input),
  reorderTeams: (input: ReorderTeamsInput) => ipc.invoke(ipcChannels.reorderTeams, input),
  closeTeam: (teamId: string) => ipc.invoke(ipcChannels.closeTeam, teamId),
  disconnectTeam: (teamId: string) => ipc.invoke(ipcChannels.disconnectTeam, teamId),
  selectTeam: (teamId: string) => ipc.invoke(ipcChannels.selectTeam, teamId),
  getBenchSnapshot: (location?: BenchLocation) => ipc.invoke(ipcChannels.getBenchSnapshot, location),
  getLoopSnapshot: (location?: LoopLocation) => ipc.invoke(ipcChannels.getLoopSnapshot, location),
  createLoop: (input: CreateLoopInput, location?: LoopLocation) => ipc.invoke(ipcChannels.createLoop, input, location),
  updateLoop: (input: UpdateLoopInput, location?: LoopLocation) => ipc.invoke(ipcChannels.updateLoop, input, location),
  runLoop: (loopId: string, location?: LoopLocation) => ipc.invoke(ipcChannels.runLoop, loopId, location),
  clearLoopHistory: (loopId: string, location?: LoopLocation) => ipc.invoke(ipcChannels.clearLoopHistory, loopId, location),
  deleteLoopExecution: (loopId: string, executionId: string, location?: LoopLocation) => ipc.invoke(ipcChannels.deleteLoopExecution, loopId, executionId, location),
  deleteLoop: (loopId: string, location?: LoopLocation) => ipc.invoke(ipcChannels.deleteLoop, loopId, location),
  listAgentConversations: (agentId: string) => ipc.invoke(ipcChannels.listAgentConversations, agentId),
  resumeAgentConversation: (agentId: string, ref: BackendConversationRef) => ipc.invoke(ipcChannels.resumeAgentConversation, agentId, ref),
  readConversationMessages: (ref: BackendConversationRef, agentId: string, location?: LoopLocation) => ipc.invoke(ipcChannels.readConversationMessages, ref, agentId, location),
  createAgent: (input: CreateAgentInput) => ipc.invoke(ipcChannels.createAgent, input),
  updateAgent: (input: UpdateAgentInput) => ipc.invoke(ipcChannels.updateAgent, input),
  assignWorkItemToAgent: (agentId: string, item: WorkItem) => ipc.invoke(ipcChannels.assignWorkItemToAgent, agentId, item),
  removeWorkItemAssignment: (item: WorkItem) => ipc.invoke(ipcChannels.removeWorkItemAssignment, item),
  duplicateAgent: (agentId: string) => ipc.invoke(ipcChannels.duplicateAgent, agentId),
  moveAgentToTeam: (input: MoveAgentToTeamInput) => ipc.invoke(ipcChannels.moveAgentToTeam, input),
  reorderAgents: (input: ReorderAgentsInput) => ipc.invoke(ipcChannels.reorderAgents, input),
  saveAgentToBench: (agentId: string) => ipc.invoke(ipcChannels.saveAgentToBench, agentId),
  deployBenchTemplate: (templateId: string, teamId?: string, location?: BenchLocation) => ipc.invoke(ipcChannels.deployBenchTemplate, templateId, teamId, location),
  removeBenchTemplate: (templateId: string, location?: BenchLocation) => ipc.invoke(ipcChannels.removeBenchTemplate, templateId, location),
  restartAgent: (agentId: string) => ipc.invoke(ipcChannels.restartAgent, agentId),
  hydrateAgentHistory: (agentId: string) => ipc.invoke(ipcChannels.hydrateAgentHistory, agentId),
  closeAgent: (agentId: string) => ipc.invoke(ipcChannels.closeAgent, agentId),
  selectAgent: (agentId: string) => ipc.invoke(ipcChannels.selectAgent, agentId),
  updateSettings: (input: UpdateSettingsInput) => ipc.invoke(ipcChannels.updateSettings, input),
  getDaemonStatus: () => ipc.invoke(ipcChannels.getDaemonStatus),
  setDaemonEnabled: (enabled: boolean) => ipc.invoke(ipcChannels.setDaemonEnabled, enabled),
  getSystemPermissions: () => ipc.invoke(ipcChannels.getSystemPermissions),
  openAccessibilitySettings: () => ipc.invoke(ipcChannels.openAccessibilitySettings),
  transcribeAppleSpeech: (audioData: ArrayBuffer, options?: AppleSpeechTranscriptionOptions) => ipc.invoke(ipcChannels.transcribeAppleSpeech, audioData, options),
  quit: () => ipc.invoke(ipcChannels.quit),
  restartApp: () => ipc.invoke(ipcChannels.restartApp),
  setAgentGoal: (agentId: string, objective: string) => ipc.invoke(ipcChannels.setAgentGoal, agentId, objective),
  clearAgentGoal: (agentId: string) => ipc.invoke(ipcChannels.clearAgentGoal, agentId),
  setAgentApprovalPreset: (agentId: string, preset: ApprovalPreset) => ipc.invoke(ipcChannels.setAgentApprovalPreset, agentId, preset),
  sendPrompt: (agentId: string, prompt: string, options?: SendPromptOptions) => ipc.invoke(ipcChannels.sendPrompt, agentId, prompt, options),
  steerPrompt: (agentId: string, prompt: string) => ipc.invoke(ipcChannels.steerPrompt, agentId, prompt),
  interruptAgent: (agentId: string) => ipc.invoke(ipcChannels.interruptAgent, agentId),
  deleteMessage: (agentId: string, messageId: string) => ipc.invoke(ipcChannels.deleteMessage, agentId, messageId),
  editMessage: (agentId: string, messageId: string, prompt: string) => ipc.invoke(ipcChannels.editMessage, agentId, messageId, prompt),
  retryMessage: (agentId: string, messageId: string) => ipc.invoke(ipcChannels.retryMessage, agentId, messageId),
  respondToClientRequest: (response: ClientRequestResponse) => ipc.invoke(ipcChannels.respondToClientRequest, response),
  onEvent: (listener: (event: MainToRendererEvent) => void) => {
    return ipc.on(ipcChannels.event, listener);
  },
  onAppCommand: (listener: (command: AppCommand) => void) => {
    return ipc.on(ipcChannels.appCommand, listener);
  },
};

contextBridge.exposeInMainWorld('codexClaw', api);
