import { contextBridge, ipcRenderer } from 'electron';
import type { AddSshConnectionInput, AgentGitBranchInput, AgentGitCommitInput, AgentGitMergeInput, AgentGitMessageGenerationInput, AgentGitPullRequestInput, AgentGitPushInput, AgentGitStageInput, AgentGitUpdateFromBaseInput, AppCommand, ApprovalPreset, BackendConversationRef, BrowserBounds, ClientRequestResponse, AppApi, ConversationListInput, ConversationResumeTarget, CreateAgentInput, CreateAutomationInput, CreateQuickChatInput, CreateSourceWorktreeInput, CreateTeamInput, DevicePairingSession, DesktopUpdateStatus, DuplicateAgentOptions, GlobalWorkItemQuery, AutomationLocation, MainToRendererEvent, MoveAgentToTeamInput, OpenInApplication, RendererSendPromptOptions, ReorderAgentsInput, ReorderRepositoriesInput, ReorderTeamsInput, SetCodexResourceSharingInput, SourceFolderListInput, SpokenAnnouncementVoice, UpdateAgentInput, UpdateAutomationInput, UpdateRemoteConnectionInput, UpdateSettingsInput, UpdateTeamInput, WorkBacklogConfigurationInput, WorkItem, WorkItemQuery, WorkProviderKind } from '@workspace/core/contracts';
import { ipcChannels, type AppIpcEvents, type AppIpcRequests } from '@workspace/core/ipc';
import { exposeCodexNativeRendererApi, TypedIpcRenderer } from '@codex-app-sdk/electron/preload';

const ipc = new TypedIpcRenderer<AppIpcRequests, AppIpcEvents>(ipcRenderer);

const api: AppApi = {
  startVisualize: (agentId, input) => ipc.invoke(ipcChannels.startVisualize, agentId, input),
  setVisualizeOpen: (agentId, input) => ipc.invoke(ipcChannels.setVisualizeOpen, agentId, input),
  generateVisualizationSuggestion: (agentId, input) => ipc.invoke(ipcChannels.generateVisualizationSuggestion, agentId, input),
  selectVisualization: (agentId, input) => ipc.invoke(ipcChannels.selectVisualization, agentId, input),
  deleteVisualization: (agentId, input) => ipc.invoke(ipcChannels.deleteVisualization, agentId, input),
  saveVisualizationCanvas: (agentId, input) => ipc.invoke(ipcChannels.saveVisualizationCanvas, agentId, input),
  readVisualizationAsset: (agentId, visualizationId) => ipc.invoke(ipcChannels.readVisualizationAsset, agentId, visualizationId),
  startCodeReview: (agentId, input) => ipc.invoke(ipcChannels.startCodeReview, agentId, input),
  decideCodeReviewFinding: (agentId, input) => ipc.invoke(ipcChannels.decideCodeReviewFinding, agentId, input),
  discussCodeReviewFinding: (agentId, input) => ipc.invoke(ipcChannels.discussCodeReviewFinding, agentId, input),
  submitCodeReviewRound: (agentId, sessionId) => ipc.invoke(ipcChannels.submitCodeReviewRound, agentId, sessionId),
  finishCodeReview: (agentId, sessionId) => ipc.invoke(ipcChannels.finishCodeReview, agentId, sessionId),
  discardCodeReview: (agentId, sessionId) => ipc.invoke(ipcChannels.discardCodeReview, agentId, sessionId),
  reviewCodeAgain: (agentId, sessionId) => ipc.invoke(ipcChannels.reviewCodeAgain, agentId, sessionId),
  respondToThreadFlag: (agentId, response) => ipc.invoke(ipcChannels.respondToThreadFlag, agentId, response),
  getSnapshot: () => ipc.invoke(ipcChannels.getSnapshot),
  getSnapshotState: () => ipc.invoke(ipcChannels.getSnapshotState),
  listSshHosts: () => ipc.invoke(ipcChannels.listSshHosts),
  addSshConnection: (input: AddSshConnectionInput) => ipc.invoke(ipcChannels.addSshConnection, input),
  checkRemoteConnection: (connectionId: string, inspectOnly?: boolean) => ipc.invoke(ipcChannels.checkRemoteConnection, connectionId, inspectOnly),
  updateRemoteConnection: (connectionId: string, input: UpdateRemoteConnectionInput) => ipc.invoke(ipcChannels.updateRemoteConnection, connectionId, input),
  removeRemoteConnection: (connectionId: string) => ipc.invoke(ipcChannels.removeRemoteConnection, connectionId),
  getRemoteControlStatus: () => ipc.invoke(ipcChannels.getRemoteControlStatus),
  enableRemoteControl: () => ipc.invoke(ipcChannels.enableRemoteControl),
  disableRemoteControl: () => ipc.invoke(ipcChannels.disableRemoteControl),
  startDevicePairing: () => ipc.invoke(ipcChannels.startDevicePairing),
  checkDevicePairing: (session: DevicePairingSession) => ipc.invoke(ipcChannels.checkDevicePairing, session),
  listPairedDevices: (environmentId: string) => ipc.invoke(ipcChannels.listPairedDevices, environmentId),
  revokePairedDevice: (environmentId: string, clientId: string) => ipc.invoke(ipcChannels.revokePairedDevice, environmentId, clientId),
  connectWorkProvider: (provider: WorkProviderKind) => ipc.invoke(ipcChannels.connectWorkProvider, provider),
  respondToPlanReview: (agentId, response) => ipc.invoke(ipcChannels.respondToPlanReview, agentId, response),
  pollWorkProviderAuthorization: (provider: WorkProviderKind) => ipc.invoke(ipcChannels.pollWorkProviderAuthorization, provider),
  disconnectWorkProvider: (provider: WorkProviderKind) => ipc.invoke(ipcChannels.disconnectWorkProvider, provider),
  listWorkSources: (provider: WorkProviderKind, location?: AutomationLocation) => ipc.invoke(ipcChannels.listWorkSources, provider, location),
  configureWorkBacklog: (input: WorkBacklogConfigurationInput, location?: AutomationLocation) => ipc.invoke(ipcChannels.configureWorkBacklog, input, location),
  listGlobalWorkItems: (provider: WorkProviderKind, location?: AutomationLocation, query?: GlobalWorkItemQuery) => ipc.invoke(ipcChannels.listGlobalWorkItems, provider, location, query),
  listAssignedWorkItems: (provider: WorkProviderKind, location?: AutomationLocation) => ipc.invoke(ipcChannels.listAssignedWorkItems, provider, location),
  listWorkItems: (provider: WorkProviderKind, repositoryId: string, location?: AutomationLocation, query?: WorkItemQuery) => ipc.invoke(ipcChannels.listWorkItems, provider, repositoryId, location, query),
  listBackendModels: (agentId, backend) => backend === undefined ? ipc.invoke(ipcChannels.listBackendModels, agentId) : ipc.invoke(ipcChannels.listBackendModels, agentId, backend),
  listBackendPlugins: (agentId: string) => ipc.invoke(ipcChannels.listBackendPlugins, agentId),
  listBackendSkills: (agentId: string) => ipc.invoke(ipcChannels.listBackendSkills, agentId),
  listAgentFiles: (agentId: string) => ipc.invoke(ipcChannels.listAgentFiles, agentId),
  previewAgentFile: (agentId: string, filePath: string) => ipc.invoke(ipcChannels.previewAgentFile, agentId, filePath),
  readAgentFileChunk: (agentId, filePath, offset) => ipc.invoke(ipcChannels.readAgentFileChunk, agentId, filePath, offset),
  getAgentGitDiff: (agentId: string, target?: import('@workspace/core/contracts').AgentGitDiffTarget) => ipc.invoke(ipcChannels.getAgentGitDiff, agentId, target),
  getAgentGitWorkflow: (agentId: string) => ipc.invoke(ipcChannels.getAgentGitWorkflow, agentId),
  listAgentTasks: (agentId: string) => ipc.invoke(ipcChannels.listAgentTasks, agentId),
  cancelAgentTask: (agentId: string, taskId: string) => ipc.invoke(ipcChannels.cancelAgentTask, agentId, taskId),
  generateAgentGitMessage: (agentId: string, input: AgentGitMessageGenerationInput) => ipc.invoke(ipcChannels.generateAgentGitMessage, agentId, input),
  stageAgentGitFiles: (agentId: string, input: AgentGitStageInput) => ipc.invoke(ipcChannels.stageAgentGitFiles, agentId, input),
  commitAgentGitChanges: (agentId: string, input: AgentGitCommitInput) => ipc.invoke(ipcChannels.commitAgentGitChanges, agentId, input),
  pushAgentGitBranch: (agentId: string, input: AgentGitPushInput) => ipc.invoke(ipcChannels.pushAgentGitBranch, agentId, input),
  createAgentGitBranch: (agentId: string, input: AgentGitBranchInput) => ipc.invoke(ipcChannels.createAgentGitBranch, agentId, input),
  createAgentGitPullRequest: (agentId: string, input: AgentGitPullRequestInput) => ipc.invoke(ipcChannels.createAgentGitPullRequest, agentId, input),
  mergeAgentGitBranch: (agentId: string, input: AgentGitMergeInput) => ipc.invoke(ipcChannels.mergeAgentGitBranch, agentId, input),
  updateAgentGitBranchFromBase: (agentId: string, input: AgentGitUpdateFromBaseInput) => ipc.invoke(ipcChannels.updateAgentGitBranchFromBase, agentId, input),
  pullAgentGitBranch: (agentId, input) => ipc.invoke(ipcChannels.pullAgentGitBranch, agentId, input),
  getOpenInApplications: () => ipc.invoke(ipcChannels.getOpenInApplications),
  openAgentPath: (agentId: string, application: OpenInApplication, filePath?: string) => ipc.invoke(ipcChannels.openAgentPath, agentId, application, filePath),
  chooseAgentFolder: () => ipc.invoke(ipcChannels.chooseAgentFolder),
  chooseCodexBinary: () => ipc.invoke(ipcChannels.chooseCodexBinary),
  chooseSourceFolder: () => ipc.invoke(ipcChannels.chooseSourceFolder),
  listSourceFolders: (input?: SourceFolderListInput) => ipc.invoke(ipcChannels.listSourceFolders, input),
  listSourceRepositories: (remoteConnectionId?: string) => ipc.invoke(ipcChannels.listSourceRepositories, remoteConnectionId),
  cloneSourceRepository: (input: import('@workspace/core/contracts').CloneSourceRepositoryInput) => ipc.invoke(ipcChannels.cloneSourceRepository, input),
  createSourceRepository: (input: import('@workspace/core/contracts').CreateSourceRepositoryInput) => ipc.invoke(ipcChannels.createSourceRepository, input),
  createProject: (input: import('@workspace/core/contracts').CreateProjectInput) => ipc.invoke(ipcChannels.createProject, input),
  listSourceBranches: (repoPath: string, remoteConnectionId?: string) => ipc.invoke(ipcChannels.listSourceBranches, repoPath, remoteConnectionId),
  listSourceWorktrees: (repoPath: string, remoteConnectionId?: string) => ipc.invoke(ipcChannels.listSourceWorktrees, repoPath, remoteConnectionId),
  suggestSourceWorktreePath: (input: Pick<CreateSourceWorktreeInput, 'branchName' | 'repoPath' | 'remoteConnectionId'>) => ipc.invoke(ipcChannels.suggestSourceWorktreePath, input),
  chooseSourceWorktreeDestination: (defaultPath: string) => ipc.invoke(ipcChannels.chooseSourceWorktreeDestination, defaultPath),
  createSourceWorktree: (input: CreateSourceWorktreeInput) => ipc.invoke(ipcChannels.createSourceWorktree, input),
  createTeam: (input: CreateTeamInput) => ipc.invoke(ipcChannels.createTeam, input),
  updateTeam: (input: UpdateTeamInput) => ipc.invoke(ipcChannels.updateTeam, input),
  reorderTeams: (input: ReorderTeamsInput) => ipc.invoke(ipcChannels.reorderTeams, input),
  closeTeam: (teamId: string) => ipc.invoke(ipcChannels.closeTeam, teamId),
  disconnectTeam: (teamId: string) => ipc.invoke(ipcChannels.disconnectTeam, teamId),
  selectTeam: (teamId: string) => ipc.invoke(ipcChannels.selectTeam, teamId),
  getAutomationSnapshot: (location?: AutomationLocation) => ipc.invoke(ipcChannels.getAutomationSnapshot, location),
  createAutomation: (input: CreateAutomationInput, location?: AutomationLocation) => ipc.invoke(ipcChannels.createAutomation, input, location),
  updateAutomation: (input: UpdateAutomationInput, location?: AutomationLocation) => ipc.invoke(ipcChannels.updateAutomation, input, location),
  runAutomation: (automationId: string, location?: AutomationLocation) => ipc.invoke(ipcChannels.runAutomation, automationId, location),
  clearAutomationHistory: (automationId: string, location?: AutomationLocation) => ipc.invoke(ipcChannels.clearAutomationHistory, automationId, location),
  deleteAutomationExecution: (automationId: string, executionId: string, location?: AutomationLocation) => ipc.invoke(ipcChannels.deleteAutomationExecution, automationId, executionId, location),
  deleteAutomation: (automationId: string, location?: AutomationLocation) => ipc.invoke(ipcChannels.deleteAutomation, automationId, location),
  listAgentConversations: (agentId: string, input?: ConversationListInput) => ipc.invoke(ipcChannels.listAgentConversations, agentId, input),
  resumeAgentConversation: (agentId: string, target: ConversationResumeTarget) => ipc.invoke(ipcChannels.resumeAgentConversation, agentId, target),
  compressAgentSession: (agentId: string) => ipc.invoke(ipcChannels.compressAgentSession, agentId),
  readConversationMessages: (ref: BackendConversationRef, agentId: string, location?: AutomationLocation) => ipc.invoke(ipcChannels.readConversationMessages, ref, agentId, location),
  createAgent: (input: CreateAgentInput) => ipc.invoke(ipcChannels.createAgent, input),
  executeMission: (input) => ipc.invoke(ipcChannels.executeMission, input),
  createMission: (input) => ipc.invoke(ipcChannels.createMission, input),
  selectMission: (missionId) => ipc.invoke(ipcChannels.selectMission, missionId),
  deleteMission: (input) => ipc.invoke(ipcChannels.deleteMission, input),
  readMissionArtifact: (missionId, stage) => ipc.invoke(ipcChannels.readMissionArtifact, missionId, stage),
  updateMission: (input) => ipc.invoke(ipcChannels.updateMission, input),
  createQuickChat: (input: CreateQuickChatInput) => ipc.invoke(ipcChannels.createQuickChat, input),
  updateAgent: (input: UpdateAgentInput) => ipc.invoke(ipcChannels.updateAgent, input),
  assignWorkItemToAgent: (agentId: string, item: WorkItem) => ipc.invoke(ipcChannels.assignWorkItemToAgent, agentId, item),
  removeWorkItemAssignment: (item: WorkItem) => ipc.invoke(ipcChannels.removeWorkItemAssignment, item),
  duplicateAgent: (agentId: string, options?: DuplicateAgentOptions) => ipc.invoke(ipcChannels.duplicateAgent, agentId, options),
  forkAgent: (agentId: string, turnId?: string) => ipc.invoke(ipcChannels.forkAgent, agentId, turnId),
  handoffAgent: (agentId, input) => ipc.invoke(ipcChannels.handoffAgent, agentId, input),
  moveAgentToTeam: (input: MoveAgentToTeamInput) => ipc.invoke(ipcChannels.moveAgentToTeam, input),
  reorderAgents: (input: ReorderAgentsInput) => ipc.invoke(ipcChannels.reorderAgents, input),
  reorderRepositories: (input: ReorderRepositoriesInput) => ipc.invoke(ipcChannels.reorderRepositories, input),
  restartAgent: (agentId: string) => ipc.invoke(ipcChannels.restartAgent, agentId),
  loadConversationHistory: (agentId: string) => ipc.invoke(ipcChannels.loadConversationHistory, agentId),
  loadOlderAgentHistory: (agentId: string) => ipc.invoke(ipcChannels.loadOlderAgentHistory, agentId),
  closeAgent: (agentId: string, input) => ipc.invoke(ipcChannels.closeAgent, agentId, input),
  selectAgent: (agentId: string) => ipc.invoke(ipcChannels.selectAgent, agentId),
  updateSettings: (input: UpdateSettingsInput) => ipc.invoke(ipcChannels.updateSettings, input),
  readEngineInstructions: (engine) => ipc.invoke(ipcChannels.readEngineInstructions, engine),
  saveEngineInstructions: (input) => ipc.invoke(ipcChannels.saveEngineInstructions, input),
  previewSpokenAnnouncementVoice: (voice: SpokenAnnouncementVoice) => ipc.invoke(ipcChannels.previewSpokenAnnouncementVoice, voice),
  getCodexResourceSharingStatus: () => ipc.invoke(ipcChannels.getCodexResourceSharingStatus),
  setCodexResourceSharing: (input: SetCodexResourceSharingInput) => ipc.invoke(ipcChannels.setCodexResourceSharing, input),
  getPluginStatus: () => ipc.invoke(ipcChannels.getPluginStatus),
  getCodexAuthentication: (remoteConnectionId?: string) => ipc.invoke(ipcChannels.getCodexAuthentication, remoteConnectionId),
  getClaudeAuthentication: (remoteConnectionId?: string) => ipc.invoke(ipcChannels.getClaudeAuthentication, remoteConnectionId),
  getProviderSetup: remoteConnectionId => ipc.invoke(ipcChannels.getProviderSetup, remoteConnectionId),
  getProviderConnections: (remoteConnectionId) => ipc.invoke(ipcChannels.getProviderConnections, remoteConnectionId),
  getProviderUsage: (backend) => ipc.invoke(ipcChannels.getProviderUsage, backend),
  setProviderEnabled: (backend, enabled, remoteConnectionId) => ipc.invoke(ipcChannels.setProviderEnabled, backend, enabled, remoteConnectionId),
  disconnectProvider: (backend, remoteConnectionId) => ipc.invoke(ipcChannels.disconnectProvider, backend, remoteConnectionId),
  authenticateProvider: (backend, action) => ipc.invoke(ipcChannels.authenticateProvider, backend, action),
  configureProviderSetup: (backend, choice) => ipc.invoke(ipcChannels.configureProviderSetup, backend, choice),
  installProvider: (backend, remoteConnectionId) => ipc.invoke(ipcChannels.installProvider, backend, remoteConnectionId),
  cancelCodexChatGptLogin: (remoteConnectionId?: string, loginId?: string) => ipc.invoke(ipcChannels.cancelCodexChatGptLogin, remoteConnectionId, loginId),
  startCodexChatGptDeviceCodeLogin: (remoteConnectionId: string) => ipc.invoke(ipcChannels.startCodexChatGptDeviceCodeLogin, remoteConnectionId),
  startCodexChatGptLogin: () => ipc.invoke(ipcChannels.startCodexChatGptLogin),
  logoutCodex: () => ipc.invoke(ipcChannels.logoutCodex),
  getUpdateStatus: () => ipc.invoke(ipcChannels.getUpdateStatus),
  installUpdate: () => ipc.invoke(ipcChannels.installUpdate),
  setDockBadgeCount: (count: number) => ipc.invoke(ipcChannels.setDockBadgeCount, count),
  getDaemonStatus: () => ipc.invoke(ipcChannels.getDaemonStatus),
  setDaemonEnabled: (enabled: boolean) => ipc.invoke(ipcChannels.setDaemonEnabled, enabled),
  getSystemPermissions: () => ipc.invoke(ipcChannels.getSystemPermissions),
  openAccessibilitySettings: () => ipc.invoke(ipcChannels.openAccessibilitySettings),
  openScreenRecordingSettings: () => ipc.invoke(ipcChannels.openScreenRecordingSettings),
  launchChatGptApp: (input) => ipc.invoke(ipcChannels.launchChatGptApp, input),
  quit: () => ipc.invoke(ipcChannels.quit),
  setMenuBarVisible: (visible) => ipc.invoke(ipcChannels.setMenuBarVisible, visible),
  restartApp: () => ipc.invoke(ipcChannels.restartApp),
  reloadRenderer: () => ipc.invoke(ipcChannels.reloadRenderer),
  setAgentGoal: (agentId: string, objective: string) => ipc.invoke(ipcChannels.setAgentGoal, agentId, objective),
  clearAgentGoal: (agentId: string) => ipc.invoke(ipcChannels.clearAgentGoal, agentId),
  setAgentApprovalPreset: (agentId: string, preset: ApprovalPreset) => ipc.invoke(ipcChannels.setAgentApprovalPreset, agentId, preset),
  setAgentPermissionMode: (agentId: string, mode: string) => ipc.invoke(ipcChannels.setAgentPermissionMode, agentId, mode),
  sendPrompt: (agentId: string, prompt: string, options?: RendererSendPromptOptions) => ipc.invoke(ipcChannels.sendPrompt, agentId, prompt, options),
  steerPrompt: (agentId: string, prompt: string, options?: RendererSendPromptOptions) => ipc.invoke(ipcChannels.steerPrompt, agentId, prompt, options),
  deleteQueuedPrompt: (agentId: string, promptId: string) => ipc.invoke(ipcChannels.deleteQueuedPrompt, agentId, promptId),
  updateQueuedPrompt: (agentId: string, promptId: string, prompt: string) => ipc.invoke(ipcChannels.updateQueuedPrompt, agentId, promptId, prompt),
  steerQueuedPrompt: (agentId: string, promptId: string, prompt?: string) => ipc.invoke(ipcChannels.steerQueuedPrompt, agentId, promptId, prompt),
  interruptAgent: (agentId: string) => ipc.invoke(ipcChannels.interruptAgent, agentId),
  deleteTurn: (agentId: string, turnId: string) => ipc.invoke(ipcChannels.deleteTurn, agentId, turnId),
  editTurn: (agentId: string, turnId: string, content: string) => ipc.invoke(ipcChannels.editTurn, agentId, turnId, content),
  retryTurn: (agentId: string, turnId: string) => ipc.invoke(ipcChannels.retryTurn, agentId, turnId),
  continueInterruptedTurn: (agentId: string) => ipc.invoke(ipcChannels.continueInterruptedTurn, agentId),
  browserOpen: (agentId: string, browserId: string, url: string, guestWebContentsId: number) => ipc.invoke(ipcChannels.browserOpen, agentId, browserId, url, guestWebContentsId),
  browserOpenVisualization: (agentId: string, browserId: string, path: string, title: string, guestWebContentsId: number) => ipc.invoke(ipcChannels.browserOpenVisualization, agentId, browserId, path, title, guestWebContentsId),
  browserNavigate: (agentId: string, browserId: string, url: string) => ipc.invoke(ipcChannels.browserNavigate, agentId, browserId, url),
  browserGoBack: (agentId: string, browserId: string) => ipc.invoke(ipcChannels.browserGoBack, agentId, browserId),
  browserGoForward: (agentId: string, browserId: string) => ipc.invoke(ipcChannels.browserGoForward, agentId, browserId),
  browserReload: (agentId: string, browserId: string) => ipc.invoke(ipcChannels.browserReload, agentId, browserId),
  browserGetZoom: (agentId: string, browserId: string) => ipc.invoke(ipcChannels.browserGetZoom, agentId, browserId),
  browserSetZoom: (agentId: string, browserId: string, percent: number) => ipc.invoke(ipcChannels.browserSetZoom, agentId, browserId, percent),
  browserCopyScreenshot: (agentId: string, browserId: string, rect?: BrowserBounds) => ipc.invoke(ipcChannels.browserCopyScreenshot, agentId, browserId, rect),
  browserSetBounds: (agentId: string, browserId: string, bounds: import('@workspace/core/contracts').BrowserViewportBounds) => ipc.invoke(ipcChannels.browserSetBounds, agentId, browserId, bounds),
  browserSetVisible: (agentId: string, browserId: string, visible: boolean) => ipc.invoke(ipcChannels.browserSetVisible, agentId, browserId, visible),
  browserSetAnnotationMode: (agentId: string, browserId: string, enabled: boolean) => ipc.invoke(ipcChannels.browserSetAnnotationMode, agentId, browserId, enabled),
  browserResolveAnnotation: (token: string, comment: string | null) => ipc.invoke(ipcChannels.browserResolveAnnotation, token, comment),
  browserClearAnnotations: (agentId: string, browserId: string) => ipc.invoke(ipcChannels.browserClearAnnotations, agentId, browserId),
  browserClose: (agentId: string, browserId: string) => ipc.invoke(ipcChannels.browserClose, agentId, browserId),
  respondToClientRequest: (response: ClientRequestResponse) => ipc.invoke(ipcChannels.respondToClientRequest, response),
  onEvent: (listener: (event: MainToRendererEvent) => void) => {
    return ipc.on(ipcChannels.event, listener);
  },
  onAppCommand: (listener: (command: AppCommand) => void) => {
    return ipc.on(ipcChannels.appCommand, listener);
  },
  onUpdateStatusChanged: (listener: (status: DesktopUpdateStatus) => void) => {
    return ipc.on(ipcChannels.updateStatusChanged, listener);
  },
};

contextBridge.exposeInMainWorld('app', api);
exposeCodexNativeRendererApi(contextBridge, ipcRenderer);
