export const ipcChannels = {
  getSnapshot: 'app:get-snapshot',
  listCodexModels: 'codex:models:list',
  listCodexSkills: 'codex:skills:list',
  listAgentFiles: 'agent:files:list',
  chooseAgentFolder: 'agent:choose-folder',
  createTeam: 'team:create',
  updateTeam: 'team:update',
  closeTeam: 'team:close',
  selectTeam: 'team:select',
  createAgent: 'agent:create',
  updateAgent: 'agent:update',
  duplicateAgent: 'agent:duplicate',
  moveAgentToTeam: 'agent:move-to-team',
  saveAgentToBench: 'agent:save-to-bench',
  deployBenchTemplate: 'bench:deploy-template',
  removeBenchTemplate: 'bench:remove-template',
  restartAgent: 'agent:restart',
  closeAgent: 'agent:close',
  selectAgent: 'agent:select',
  selectAgentFolder: 'agent:select-folder',
  updateSettings: 'settings:update',
  transcribeAppleSpeech: 'transcription:apple-speech',
  quit: 'app:quit',
  sendPrompt: 'agent:send-prompt',
  steerPrompt: 'agent:steer-prompt',
  interruptAgent: 'agent:interrupt',
  respondToClientRequest: 'client-request:respond',
  event: 'app:event',
  appCommand: 'app:command',
} as const;

export type IpcChannel = typeof ipcChannels[keyof typeof ipcChannels];
