export const backendMethods = {
  engineInstructionsRead: 'settings/instructions/read',
  engineInstructionsSave: 'settings/instructions/save',
  agentApprovalPresetUpdate: 'agent/approvalPreset/update',
  agentCodeReviewStart: 'agent/codeReview/start',
  agentCodeReviewFindingDecide: 'agent/codeReview/finding/decide',
  agentCodeReviewFindingDiscuss: 'agent/codeReview/finding/discuss',
  agentCodeReviewRoundSubmit: 'agent/codeReview/round/submit',
  agentCodeReviewFinish: 'agent/codeReview/finish',
  agentCodeReviewDiscard: 'agent/codeReview/discard',
  agentCodeReviewAgain: 'agent/codeReview/again',
  agentConversationMessagesGet: 'agent/conversation/messages/get',
  agentConversationResume: 'agent/conversation/resume',
  agentConversationReplaceWithSummary: 'agent/conversation/replaceWithSummary',
  agentConversationsList: 'agent/conversations/list',
  agentCreate: 'agent/create',
  agentQuickChatCreate: 'agent/quickChat/create',
  agentDelete: 'agent/delete',
  agentDuplicate: 'agent/duplicate',
  agentFork: 'agent/fork',
  agentFilePreview: 'agent/file/preview',
  agentFilesList: 'agent/files/list',
  workspaceFolderValidate: 'workspace/folder/validate',
  agentGitDiffGet: 'agent/git/diff/get',
  agentGitWorkflowGet: 'agent/git/workflow/get',
  agentGitMessageGenerate: 'agent/git/message/generate',
  agentGitStage: 'agent/git/stage',
  agentGitCommit: 'agent/git/commit',
  agentGitPush: 'agent/git/push',
  agentGitBranchCreate: 'agent/git/branch/create',
  agentGitPullRequestCreate: 'agent/git/pullRequest/create',
  agentGitMerge: 'agent/git/merge',
  agentGitUpdateFromBase: 'agent/git/base/update',
  agentGoalClear: 'agent/goal/clear',
  agentGoalUpdate: 'agent/goal/update',
  agentConversationLoad: 'agent/conversation/load',
  agentConversationHistoryLoadOlder: 'agent/conversation/history/loadOlder',
  agentInterrupt: 'agent/interrupt',
  agentTurnDelete: 'agent/turn/delete',
  agentTurnEdit: 'agent/turn/edit',
  agentTurnRetry: 'agent/turn/retry',
  agentModelsList: 'agent/models/list',
  agentPluginsList: 'agent/plugins/list',
  clientAgentExternalApplicationUpdate: 'client/agentExternalApplication/update',
  agentPermissionModeUpdate: 'agent/permissionMode/update',
  agentPromptSend: 'agent/prompt/send',
  agentPlanReviewRespond: 'agent/planReview/respond',
  agentThreadFlagRespond: 'agent/threadFlag/respond',
  agentPromptSteer: 'agent/prompt/steer',
  agentQueuedPromptDelete: 'agent/queuedPrompt/delete',
  agentQueuedPromptSteer: 'agent/queuedPrompt/steer',
  agentQueuedPromptUpdate: 'agent/queuedPrompt/update',
  clientAgentOrderUpdate: 'client/agentOrder/update',
  agentConversationReset: 'agent/conversation/reset',
  clientNavigationSelectAgent: 'client/navigation/selectAgent',
  agentSkillsList: 'agent/skills/list',
  agentTeamMove: 'agent/team/move',
  agentUpdate: 'agent/update',
  agentWorkItemAssign: 'agent/workItem/assign',
  agentWorkItemAssignmentDelete: 'agent/workItem/assignment/delete',
  backendEventNotify: 'backend/event/notify',
  backendHealthGet: 'backend/health/get',
  clientExternalOpen: 'client/external/open',
  clientSpokenAnnouncementQueue: 'client/spokenAnnouncement/queue',
  clientBrowserOpen: 'client/browser/open',
  clientBrowserExecute: 'client/browser/execute',
  clientComputerUseExecute: 'client/computerUse/execute',
  clientComputerUseStop: 'client/computerUse/stop',
  clientComputerUseRequestAccessibility: 'client/computerUse/requestAccessibility',
  clientComputerUseStatusGet: 'client/computerUse/status/get',
  agentRequestRespond: 'agent/request/respond',
  clientStateGet: 'client/state/get',
  clientSystemPermissionsAccessibilityOpen: 'client/system/permissions/accessibility/open',
  clientSystemPermissionsGet: 'client/system/permissions/get',
  clientSystemPermissionsScreenRecordingOpen: 'client/system/permissions/screenRecording/open',
  connectionsDelete: 'connections/delete',
  connectionsSshCreate: 'connections/ssh/create',
  connectionsSshHostsList: 'connections/sshHosts/list',
  connectionsRuntimeInspect: 'connections/runtime/inspect',
  connectionsRuntimeSync: 'connections/runtime/sync',
  connectionsUpdate: 'connections/update',
  codexAuthenticationGet: 'codex/authentication/get',
  codexLoginCancel: 'codex/authentication/login/cancel',
  codexChatGptLoginStart: 'codex/authentication/chatgpt/start',
  codexChatGptDeviceCodeLoginStart: 'codex/authentication/deviceCode/start',
  codexLogout: 'codex/authentication/logout',
  driverApprovalPresetUpdate: 'driver/approvalPreset/update',
  driverCodexAuthenticationGet: 'driver/codex/authentication/get',
  driverCodexLoginCancel: 'driver/codex/authentication/login/cancel',
  driverCodexChatGptLoginStart: 'driver/codex/authentication/chatgpt/start',
  driverCodexChatGptDeviceCodeLoginStart: 'driver/codex/authentication/deviceCode/start',
  driverCodexLogout: 'driver/codex/authentication/logout',
  driverAgentRequestRespond: 'driver/agentRequest/respond',
  driverConversationMessagesGet: 'driver/conversation/messages/get',
  driverConversationSummaryGet: 'driver/conversation/summary/get',
  driverConversationFork: 'driver/conversation/fork',
  driverConversationArchive: 'driver/conversation/archive',
  driverConversationResume: 'driver/conversation/resume',
  driverConversationReplaceWithSummary: 'driver/conversation/replaceWithSummary',
  driverConversationTitleUpdate: 'driver/conversation/title/update',
  driverConversationsList: 'driver/conversations/list',
  driverConversationsReconcile: 'driver/conversations/reconcile',
  workspaceFilePreview: 'workspace/file/preview',
  workspaceFilesList: 'workspace/files/list',
  driverTextGenerate: 'driver/text/generate',
  driverCodeReviewRun: 'driver/codeReview/run',
  driverCodeReviewDispose: 'driver/codeReview/dispose',
  driverGoalClear: 'driver/goal/clear',
  driverGoalUpdate: 'driver/goal/update',
  driverConversationLoad: 'driver/conversation/load',
  driverConversationHistoryLoadOlder: 'driver/conversation/history/loadOlder',
  driverInterrupt: 'driver/interrupt',
  driverModelsList: 'driver/models/list',
  driverPluginsList: 'driver/plugins/list',
  driverPermissionModeUpdate: 'driver/permissionMode/update',
  driverPromptCommandHandle: 'driver/promptCommand/handle',
  driverPromptSend: 'driver/prompt/send',
  driverPromptSteer: 'driver/prompt/steer',
  driverConversationRelease: 'driver/conversation/release',
  driverSkillsList: 'driver/skills/list',
  driverTurnDelete: 'driver/turn/delete',
  driverTurnEdit: 'driver/turn/edit',
  driverTurnRetry: 'driver/turn/retry',
  debugAgentMessageSend: 'debug/agentMessage/send',
  debugExecutionPlanToggle: 'debug/executionPlan/toggle',
  debugPlanReadyForReviewInject: 'debug/planReadyForReview/inject',
  debugThreadFlagSet: 'debug/threadFlag/set',
  remoteControlStatusGet: 'remoteControl/status/get',
  remoteControlEnable: 'remoteControl/enable',
  remoteControlDisable: 'remoteControl/disable',
  remoteControlPairingStart: 'remoteControl/pairing/start',
  remoteControlPairingCheck: 'remoteControl/pairing/check',
  remoteControlClientsList: 'remoteControl/clients/list',
  remoteControlClientRevoke: 'remoteControl/client/revoke',
  automationCreate: 'automation/create',
  automationDelete: 'automation/delete',
  automationExecutionDelete: 'automation/execution/delete',
  automationHistoryClear: 'automation/history/clear',
  automationRun: 'automation/run',
  automationUpdate: 'automation/update',
  settingsUpdate: 'settings/update',
  clientPreferencesUpdate: 'client/preferences/update',
  settingsCodexResourceSharingGet: 'settings/codexResourceSharing/get',
  settingsCodexResourceSharingSet: 'settings/codexResourceSharing/set',
  settingsPluginStatusGet: 'settings/pluginStatus/get',
  snapshotGet: 'snapshot/get',
  snapshotAutomationsGet: 'snapshot/automations/get',
  sourceFolderDetect: 'source/folder/detect',
  sourceFoldersList: 'source/folders/list',
  sourceRepositoriesList: 'source/repositories/list',
  sourceRepositoryClone: 'source/repository/clone',
  sourceRepositoryCreate: 'source/repository/create',
  sourceBranchesList: 'source/branches/list',
  sourceWorktreeCreate: 'source/worktree/create',
  sourceWorktreePathSuggest: 'source/worktree/path/suggest',
  sourceWorktreesList: 'source/worktrees/list',
  clientRepositoryOrderUpdate: 'client/repositoryOrder/update',
  systemPermissionsAccessibilityOpen: 'system/permissions/accessibility/open',
  systemPermissionsGet: 'system/permissions/get',
  systemPermissionsScreenRecordingOpen: 'system/permissions/screenRecording/open',
  teamCreate: 'team/create',
  teamConnect: 'team/connect',
  teamDelete: 'team/delete',
  teamDisconnect: 'team/disconnect',
  clientTeamOrderUpdate: 'client/teamOrder/update',
  clientNavigationSelectTeam: 'client/navigation/selectTeam',
  teamUpdate: 'team/update',
  workProviderBacklogConfigure: 'workProvider/backlog/configure',
  workProviderConnect: 'workProvider/connect',
  workProviderAuthorizationPoll: 'workProvider/authorization/poll',
  workProviderConnectionsReload: 'workProvider/connections/reload',
  workProviderDisconnect: 'workProvider/disconnect',
  workProviderGlobalItemsList: 'workProvider/globalItems/list',
  workProviderAssignedItemsList: 'workProvider/assignedItems/list',
  workProviderItemsList: 'workProvider/items/list',
  workProviderRepositoriesList: 'workProvider/repositories/list',
} as const;

export type BackendMethod = (typeof backendMethods)[keyof typeof backendMethods];

export const backendMethodValues = Object.values(backendMethods) as BackendMethod[];

export const agentGitBackendMethods = [
  backendMethods.agentGitDiffGet,
  backendMethods.agentGitWorkflowGet,
  backendMethods.agentGitMessageGenerate,
  backendMethods.agentGitStage,
  backendMethods.agentGitCommit,
  backendMethods.agentGitPush,
  backendMethods.agentGitBranchCreate,
  backendMethods.agentGitPullRequestCreate,
  backendMethods.agentGitMerge,
  backendMethods.agentGitUpdateFromBase,
] as const;

export type AgentGitBackendMethod = typeof agentGitBackendMethods[number];
