import { backendMethods, type BackendMethod } from './methods';

const QUICK_REQUEST_TIMEOUT_MS = 10_000;
const IO_REQUEST_TIMEOUT_MS = 30_000;
const LONG_RUNNING_REQUEST_TIMEOUT_MS = 120_000;
const EXTENDED_REQUEST_TIMEOUT_MS = 10 * 60_000;

/**
 * Every backend action must have an intentional timeout budget.
 *
 * Do not add a fallback here: when a method is added to backendMethods,
 * TypeScript must force its author to classify the operation based on the work
 * it actually performs. Use QUICK for in-memory state, IO for bounded local
 * filesystem/process work, LONG_RUNNING for provider/network/git operations,
 * and EXTENDED only for operations designed to run for several minutes.
 */
const requestTimeoutByMethod = {
  [backendMethods.clientMobileSimulatorExecute]: EXTENDED_REQUEST_TIMEOUT_MS,
  [backendMethods.clientWorkspaceGet]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.clientWorkspaceApply]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.clientDocumentRead]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.clientDocumentSave]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.agentDocumentWrite]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.agentTasksList]: QUICK_REQUEST_TIMEOUT_MS,
  [backendMethods.agentTaskCancel]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.agentHandoff]: EXTENDED_REQUEST_TIMEOUT_MS,
  [backendMethods.driverHandoffCheck]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.providerUsageGet]: IO_REQUEST_TIMEOUT_MS,
  [backendMethods.driverAccountRateLimitsGet]: IO_REQUEST_TIMEOUT_MS,
  [backendMethods.providerConnectionsGet]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.providerEnabledSet]: IO_REQUEST_TIMEOUT_MS,
  [backendMethods.providerDisconnect]: IO_REQUEST_TIMEOUT_MS,
  [backendMethods.providerAuthenticate]: EXTENDED_REQUEST_TIMEOUT_MS,
  [backendMethods.providerSetupGet]: IO_REQUEST_TIMEOUT_MS,
  [backendMethods.providerSetupConfigure]: IO_REQUEST_TIMEOUT_MS,
  [backendMethods.providerRefresh]: IO_REQUEST_TIMEOUT_MS,
  [backendMethods.engineInstructionsRead]: IO_REQUEST_TIMEOUT_MS,
  [backendMethods.engineInstructionsSave]: IO_REQUEST_TIMEOUT_MS,
  [backendMethods.agentApprovalPresetUpdate]: QUICK_REQUEST_TIMEOUT_MS,
  [backendMethods.agentCodeReviewStart]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.agentCodeReviewFindingDecide]: QUICK_REQUEST_TIMEOUT_MS,
  [backendMethods.agentCodeReviewFindingDiscuss]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.agentCodeReviewRoundSubmit]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.agentCodeReviewFinish]: QUICK_REQUEST_TIMEOUT_MS,
  [backendMethods.agentCodeReviewDiscard]: QUICK_REQUEST_TIMEOUT_MS,
  [backendMethods.agentCodeReviewAgain]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.agentVisualizeStart]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.agentVisualizeOpenSet]: QUICK_REQUEST_TIMEOUT_MS,
  [backendMethods.agentVisualizationSuggestionGenerate]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.agentVisualizationSelect]: QUICK_REQUEST_TIMEOUT_MS,
  [backendMethods.agentVisualizationDelete]: QUICK_REQUEST_TIMEOUT_MS,
  [backendMethods.agentVisualizationCanvasSave]: IO_REQUEST_TIMEOUT_MS,
  [backendMethods.agentVisualizationAssetGet]: IO_REQUEST_TIMEOUT_MS,
  [backendMethods.agentConversationMessagesGet]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.agentConversationResume]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.agentConversationReplaceWithSummary]: EXTENDED_REQUEST_TIMEOUT_MS,
  [backendMethods.agentConversationsList]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.agentCreate]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.missionExecute]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.missionCreate]: IO_REQUEST_TIMEOUT_MS,
  [backendMethods.missionDelete]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.missionArtifactRead]: IO_REQUEST_TIMEOUT_MS,
  [backendMethods.missionUpdate]: IO_REQUEST_TIMEOUT_MS,
  [backendMethods.agentQuickChatCreate]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.agentDelete]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.agentDuplicate]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.agentFork]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.agentFilePreview]: IO_REQUEST_TIMEOUT_MS,
  [backendMethods.agentFileChunkRead]: IO_REQUEST_TIMEOUT_MS,
  [backendMethods.agentFilesList]: IO_REQUEST_TIMEOUT_MS,
  [backendMethods.workspaceFolderValidate]: IO_REQUEST_TIMEOUT_MS,
  [backendMethods.agentGitDiffGet]: IO_REQUEST_TIMEOUT_MS,
  [backendMethods.agentGitWorkflowGet]: IO_REQUEST_TIMEOUT_MS,
  [backendMethods.agentGitMessageGenerate]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.agentGitStage]: IO_REQUEST_TIMEOUT_MS,
  [backendMethods.agentGitCommit]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.agentGitPush]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.agentGitBranchCreate]: IO_REQUEST_TIMEOUT_MS,
  [backendMethods.agentGitPullRequestCreate]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.agentGitMerge]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.agentGitUpdateFromBase]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.agentGitPull]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.agentGitRevert]: IO_REQUEST_TIMEOUT_MS,
  [backendMethods.agentGoalClear]: QUICK_REQUEST_TIMEOUT_MS,
  [backendMethods.agentGoalUpdate]: QUICK_REQUEST_TIMEOUT_MS,
  [backendMethods.agentConversationLoad]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.agentConversationHistoryLoadOlder]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.agentInterrupt]: QUICK_REQUEST_TIMEOUT_MS,
  [backendMethods.agentTurnDelete]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.agentTurnEdit]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.agentTurnRetry]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.agentTurnContinueInterrupted]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.agentModelsList]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.agentPluginsList]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.clientAgentExternalApplicationUpdate]: QUICK_REQUEST_TIMEOUT_MS,
  [backendMethods.agentPermissionModeUpdate]: QUICK_REQUEST_TIMEOUT_MS,
  [backendMethods.agentPromptSend]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.agentPlanReviewRespond]: QUICK_REQUEST_TIMEOUT_MS,
  [backendMethods.agentThreadFlagRespond]: QUICK_REQUEST_TIMEOUT_MS,
  [backendMethods.agentPromptSteer]: QUICK_REQUEST_TIMEOUT_MS,
  [backendMethods.agentQueuedPromptDelete]: QUICK_REQUEST_TIMEOUT_MS,
  [backendMethods.agentQueuedPromptSteer]: QUICK_REQUEST_TIMEOUT_MS,
  [backendMethods.agentQueuedPromptUpdate]: QUICK_REQUEST_TIMEOUT_MS,
  [backendMethods.clientAgentOrderUpdate]: QUICK_REQUEST_TIMEOUT_MS,
  [backendMethods.agentConversationReset]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.clientNavigationSelectAgent]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.agentSkillsList]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.agentTeamMove]: QUICK_REQUEST_TIMEOUT_MS,
  [backendMethods.agentUpdate]: QUICK_REQUEST_TIMEOUT_MS,
  [backendMethods.agentWorkItemAssign]: QUICK_REQUEST_TIMEOUT_MS,
  [backendMethods.agentWorkItemAssignmentDelete]: QUICK_REQUEST_TIMEOUT_MS,
  [backendMethods.backendEventNotify]: QUICK_REQUEST_TIMEOUT_MS,
  [backendMethods.backendHealthGet]: QUICK_REQUEST_TIMEOUT_MS,
  [backendMethods.clientExternalOpen]: QUICK_REQUEST_TIMEOUT_MS,
  [backendMethods.clientSpokenAnnouncementQueue]: QUICK_REQUEST_TIMEOUT_MS,
  [backendMethods.clientBrowserOpen]: IO_REQUEST_TIMEOUT_MS,
  [backendMethods.clientBrowserExecute]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.clientComputerUseExecute]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.clientComputerUseStop]: QUICK_REQUEST_TIMEOUT_MS,
  [backendMethods.clientComputerUseRequestAccessibility]: IO_REQUEST_TIMEOUT_MS,
  [backendMethods.clientComputerUseStatusGet]: QUICK_REQUEST_TIMEOUT_MS,
  [backendMethods.agentRequestRespond]: QUICK_REQUEST_TIMEOUT_MS,
  [backendMethods.clientStateGet]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.clientSystemPermissionsAccessibilityOpen]: IO_REQUEST_TIMEOUT_MS,
  [backendMethods.clientSystemPermissionsGet]: IO_REQUEST_TIMEOUT_MS,
  [backendMethods.clientSystemPermissionsScreenRecordingOpen]: IO_REQUEST_TIMEOUT_MS,
  [backendMethods.connectionsDelete]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.connectionsSshCreate]: EXTENDED_REQUEST_TIMEOUT_MS,
  [backendMethods.connectionsSshHostsList]: IO_REQUEST_TIMEOUT_MS,
  [backendMethods.connectionsRuntimeInspect]: EXTENDED_REQUEST_TIMEOUT_MS,
  [backendMethods.connectionsRuntimeSync]: EXTENDED_REQUEST_TIMEOUT_MS,
  [backendMethods.connectionsUpdate]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.codexAuthenticationGet]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.claudeAuthenticationGet]: IO_REQUEST_TIMEOUT_MS,
  [backendMethods.codexLoginCancel]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.codexChatGptLoginStart]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.codexChatGptDeviceCodeLoginStart]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.codexLogout]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.driverApprovalPresetUpdate]: QUICK_REQUEST_TIMEOUT_MS,
  [backendMethods.driverCodexAuthenticationGet]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.driverProviderAuthentication]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.driverCodexLoginCancel]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.driverCodexChatGptLoginStart]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.driverCodexChatGptDeviceCodeLoginStart]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.driverCodexLogout]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.driverAgentRequestRespond]: QUICK_REQUEST_TIMEOUT_MS,
  [backendMethods.driverConversationMessagesGet]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.driverConversationSummaryGet]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.driverConversationFork]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.driverConversationArchive]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.driverConversationDelete]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.driverConversationResume]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.driverConversationReplaceWithSummary]: EXTENDED_REQUEST_TIMEOUT_MS,
  [backendMethods.driverConversationTitleUpdate]: QUICK_REQUEST_TIMEOUT_MS,
  [backendMethods.driverConversationsList]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.driverConversationsReconcile]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.workspaceFilePreview]: IO_REQUEST_TIMEOUT_MS,
  [backendMethods.workspaceFileChunkRead]: IO_REQUEST_TIMEOUT_MS,
  [backendMethods.workspaceFilesList]: IO_REQUEST_TIMEOUT_MS,
  [backendMethods.driverTextGenerate]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.driverCodeReviewRun]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.driverCodeReviewDispose]: QUICK_REQUEST_TIMEOUT_MS,
  [backendMethods.driverGoalClear]: QUICK_REQUEST_TIMEOUT_MS,
  [backendMethods.driverGoalUpdate]: QUICK_REQUEST_TIMEOUT_MS,
  [backendMethods.driverConversationLoad]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.driverConversationHistoryLoadOlder]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.driverInterrupt]: QUICK_REQUEST_TIMEOUT_MS,
  [backendMethods.driverModelsList]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.driverPluginsList]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.driverPermissionModeUpdate]: QUICK_REQUEST_TIMEOUT_MS,
  [backendMethods.driverPromptCommandHandle]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.driverPromptSend]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.driverPromptSteer]: QUICK_REQUEST_TIMEOUT_MS,
  [backendMethods.driverConversationRelease]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.driverSkillsList]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.driverTurnDelete]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.driverTurnEdit]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.driverTurnRetry]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.driverTurnContinueInterrupted]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.debugAgentMessageSend]: QUICK_REQUEST_TIMEOUT_MS,
  [backendMethods.debugExecutionPlanToggle]: QUICK_REQUEST_TIMEOUT_MS,
  [backendMethods.debugPlanReadyForReviewInject]: QUICK_REQUEST_TIMEOUT_MS,
  [backendMethods.debugMissionStageSet]: QUICK_REQUEST_TIMEOUT_MS,
  [backendMethods.debugCodeReviewSet]: QUICK_REQUEST_TIMEOUT_MS,
  [backendMethods.debugVisualizePopulate]: QUICK_REQUEST_TIMEOUT_MS,
  [backendMethods.debugThreadFlagSet]: QUICK_REQUEST_TIMEOUT_MS,
  [backendMethods.remoteControlStatusGet]: QUICK_REQUEST_TIMEOUT_MS,
  [backendMethods.remoteControlEnable]: IO_REQUEST_TIMEOUT_MS,
  [backendMethods.remoteControlDisable]: IO_REQUEST_TIMEOUT_MS,
  [backendMethods.remoteControlPairingStart]: IO_REQUEST_TIMEOUT_MS,
  [backendMethods.remoteControlPairingCheck]: IO_REQUEST_TIMEOUT_MS,
  [backendMethods.remoteControlClientsList]: IO_REQUEST_TIMEOUT_MS,
  [backendMethods.remoteControlClientRevoke]: IO_REQUEST_TIMEOUT_MS,
  [backendMethods.automationCreate]: IO_REQUEST_TIMEOUT_MS,
  [backendMethods.automationDelete]: IO_REQUEST_TIMEOUT_MS,
  [backendMethods.automationExecutionDelete]: IO_REQUEST_TIMEOUT_MS,
  [backendMethods.automationHistoryClear]: IO_REQUEST_TIMEOUT_MS,
  [backendMethods.automationRun]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.automationUpdate]: IO_REQUEST_TIMEOUT_MS,
  [backendMethods.settingsUpdate]: QUICK_REQUEST_TIMEOUT_MS,
  [backendMethods.clientPreferencesUpdate]: QUICK_REQUEST_TIMEOUT_MS,
  [backendMethods.settingsCodexResourceSharingGet]: IO_REQUEST_TIMEOUT_MS,
  [backendMethods.settingsCodexResourceSharingSet]: IO_REQUEST_TIMEOUT_MS,
  [backendMethods.settingsPluginStatusGet]: IO_REQUEST_TIMEOUT_MS,
  [backendMethods.snapshotGet]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.snapshotAutomationsGet]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.sourceFolderDetect]: IO_REQUEST_TIMEOUT_MS,
  [backendMethods.sourceFoldersList]: IO_REQUEST_TIMEOUT_MS,
  [backendMethods.sourceRepositoriesList]: IO_REQUEST_TIMEOUT_MS,
  [backendMethods.sourceRepositoryClone]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.sourceRepositoryCreate]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  // Creates a Git repository and an agent; both may need filesystem and Git I/O.
  [backendMethods.projectCreate]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.sourceBranchesList]: IO_REQUEST_TIMEOUT_MS,
  [backendMethods.sourceWorktreeCreate]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.sourceWorktreePathSuggest]: IO_REQUEST_TIMEOUT_MS,
  [backendMethods.sourceWorktreesList]: IO_REQUEST_TIMEOUT_MS,
  [backendMethods.clientRepositoryOrderUpdate]: QUICK_REQUEST_TIMEOUT_MS,
  [backendMethods.systemPermissionsAccessibilityOpen]: IO_REQUEST_TIMEOUT_MS,
  [backendMethods.systemPermissionsGet]: IO_REQUEST_TIMEOUT_MS,
  [backendMethods.systemPermissionsScreenRecordingOpen]: IO_REQUEST_TIMEOUT_MS,
  [backendMethods.teamCreate]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.teamConnect]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.teamDelete]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.teamDisconnect]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.clientTeamOrderUpdate]: QUICK_REQUEST_TIMEOUT_MS,
  [backendMethods.clientNavigationSelectTeam]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.teamUpdate]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.workProviderBacklogConfigure]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.workProviderConnect]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.workProviderAuthorizationPoll]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.workProviderConnectionsReload]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.workProviderDisconnect]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.workProviderGlobalItemsList]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.workProviderAssignedItemsList]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.workProviderItemsList]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
  [backendMethods.workProviderSourcesList]: LONG_RUNNING_REQUEST_TIMEOUT_MS,
} satisfies Record<BackendMethod, number>;

export function backendRequestTimeoutMs(method: string): number {
  const timeoutMs = requestTimeoutByMethod[method as BackendMethod];
  if (timeoutMs === undefined) {
    throw new Error(`No backend request timeout configured for ${method}.`);
  }
  return timeoutMs;
}
